In [1]:
# 1324124124
# 223345678
## testtest02060110pm
# test02061823pm

In [2]:
import requests
import pandas as pd
from datetime import datetime
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import random
from plotly.offline import init_notebook_mode
from dateutil.relativedelta import relativedelta
init_notebook_mode(connected = True)
import warnings
warnings.filterwarnings('ignore')
import os
# from scipy import stats
import json
import math
import base64
import hmac
import math
import base64
import struct
import hashlib
import time
from requests.auth import HTTPBasicAuth
import pandas as pd
from common_utils.CONFIG import *
import ccxt
base_dir = get_base_dir()
pd.set_option('display.float_format', '{:.2f}'.format)  # 改成你想要的小数位数


proxies = {'https':'127.0.0.1:7890', 'http':'127.0.0.1:7890'}


def fetch_okx_last_price(base: str) -> float:
    """
    base: 'BTC' or 'ETH'
    优先拉永续:  BTC/USDT:USDT (OKX swap)
    回退拉现货:  BTC/USDT
    返回 ticker['last'] (float)
    """
    ex = ccxt.okx({
        "enableRateLimit": True,
        "options": {"defaultType": "swap"},  # 优先 swap
    })

    # 1) swap 优先
    try:
        sym_swap = f"{base}/USDT:USDT"
        t = ex.fetch_ticker(sym_swap)
        if t.get("last") is not None:
            return float(t["last"])
    except Exception:
        pass

    # 2) 回退 spot
    ex = ccxt.okx({
        "enableRateLimit": True,
        "options": {"defaultType": "spot"},
    })
    sym_spot = f"{base}/USDT"
    t = ex.fetch_ticker(sym_spot)
    return float(t["last"])
def cal_google_code(secret_key: str):
    # secret key 的长度必须是 8 的倍数。所以如果 secret key 不符合要求，需要在后面补上相应个数的 "="
    secret_key_len = len(secret_key)
    secret_key_pad_len = math.ceil(secret_key_len / 8) * 8 - secret_key_len
    secret_key = secret_key + "=" * secret_key_pad_len

    duration_input = int(time.time()) // 30
    _key = base64.b32decode(secret_key)
    msg = struct.pack(">Q", duration_input)
    google_code = hmac.new(_key, msg, hashlib.sha1).digest()
    o = google_code[19] & 15
    google_code = str((struct.unpack(">I", google_code[o:o+4])[0] & 0x7fffffff) % 1000000)

    # 生成的验证码未必是 6 位，注意要在前面补 0
    if len(google_code) == 5:
        google_code = '0' + google_code
    return google_code


def get_cookie(_url: str, _username: str, _password: str):
    _response = requests.post(url=_url, auth=HTTPBasicAuth(_username, _password), allow_redirects=False, stream=True)
    print(_response, _response.text, _response.headers)
    _cookies = requests.utils.dict_from_cookiejar(_response.cookies)
    return _cookies

# 返回一个被两重验证的、可以使用的cookie
def login(prefix="mmadminjp"):
    s = requests.Session()
    
    username1 = 'ray_xu' # dcdl用户名
    if prefix == 'mmadminjp3':
        key1 = 'NVCX4PJP32Y4JTJJVCKU5XUQ4M' # dcdl密钥
    elif prefix == 'mmadmin':
        key1 = '7H62KCRCUEOYH2FV4SCYXYMPWE'
    password1 = cal_google_code(key1)
#     print(username1, password1)
    # 如果用http://，会被重定向为https://，可以通过headers得到
    url = f'https://{prefix}.digifinex.org/'
    login_response1 = s.post(url=url, auth=HTTPBasicAuth(username1, password1), allow_redirects=False, stream=True)
#     print(login_response1, login_response1.text, login_response1.headers)
    login_cookies1 = requests.utils.dict_from_cookiejar(login_response1.cookies)
#     print(login_cookies1)
    username2 = 'ray_xu' # dcdl用户名
    key2 = 'HBRDG6BUPJZGC6K7PB2TI3LCOM4XQNDO' # dcdl密钥
    password2 = cal_google_code(key2)
    # 这里必须再登陆一次，否则会重定向到login
    url2 = f'https://{prefix}.digifinex.org/api/login/valid'
#     print(username2, password2, url)
    data = {
        "account":username2,
        "glecode":password2,
    }
    # 不加第一次登陆的cookie会报错
    login_response2 = s.post(url=url2, data = data, headers={'User-Agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
                                                                    'Content-Type': 'application/x-www-form-urlencoded'}, 
                                    cookies = login_cookies1, allow_redirects=False)
#     print(login_response2, login_response2.text, login_response2.headers)
    login_cookies2 = requests.utils.dict_from_cookiejar(login_response2.cookies)
    
    return s, login_cookies1

In [3]:
verfied_session, verfied_cookies = login(prefix='mmadmin')
verfied_session1, verfied_cookies1 = login(prefix='mmadminjp3')

In [4]:
dc_name = pd.read_excel(f'{base_dir}/Obentech/CF环境账户对应关系0225.xlsx')
dc_name.dropna(subset=['Binance账户名','本金'],inplace=True)
dc_name = dc_name[dc_name['备注'].isna()]
dc_name.reset_index(drop=True, inplace=True)
# 新增：类型（OKX账户名包含 zy/ZY -> 内部，否则托管）
# mask_internal = dc_name['OKX账户名'].fillna('').str.contains('zy', case=False, regex=False)
# dc_name['类型'] = np.where(mask_internal, '内部', '托管')



# 公司资金（内部）
env_company = ["cfdc_dcpro1","cfdc_dcpro2","cfdc_dcpro3","cfdc_dcpro4","cfdc_dcpro5","cfdc_dcpro7",
               "cfdc_dcpro8","cfdc_dcpro9","cfdc_dcpro12","cfdc_dcpro13","cfdc_dcpro15","cfdc_dcpro16",
               "cfdc_dcpro17","cfdc_dcpro22","cfdc_dcpro24","cfdc_dcpro26","cfdc_dcpro27","cfdc_dcpro29"]

# 客户资金（托管）
env_client = ["cfdc_dcpro6","cfdc_dcpro10","cfdc_dcpro11","cfdc_dcpro14","cfdc_dcpro18","cfdc_dcpro19",
              "cfdc_dcpro20","cfdc_dcpro21","cfdc_dcpro25","cfdc_dcpro28","cfdc_dcpro30","cfdc_dcpro31",
              "cfdc_dcpro32","cfdc_dcpro33","cfdc_dcpro34","cfdc_dcpro35","cfdc_dcpro36","cfdc_dcpro38","cfdc_dcbb1"]

type_map = {e: "内部" for e in env_company}
type_map.update({e: "托管" for e in env_client})

dc_name["类型"] = dc_name["跨所环境"].map(type_map).fillna("未知")



dc_name

,排序,跨所环境,本金,Binance本金,OKX本金,Binance环境,Binance账户名,OKX环境,OKX账户名,备注,类型
0,NaN,cfdc_dcbb1,BTC,7.50,7.50,bn_v5_pm_pro43,ltpbn30012,bybit5_v5_by3,LPbybit644,NaN,托管
1,NaN,cfdc_dcpro1,USDT,500000.00,500000.00,bn_v5_pm_pro5,binancetfmmtest50@dftstat.com,okx_v5_test12,Okzyusdt02,NaN,内部
2,NaN,cfdc_dcpro10,BTC,5.00,5.00,bn_v5_pm_pro15,cf09ran20250423_virtual@n9nik8gxmanagedsub.com,okx_v5_test44,cf09ran20250423okx,NaN,托管
3,NaN,cfdc_dcpro11,BTC,3.50,6.50,bn_v5_pm_pro7,cf10ran20250423_virtual@ftleog2vmanagedsub.com,okx_v5_test45,cf10ran20250423okx,NaN,托管
4,NaN,cfdc_dcpro12,BTC,6.00,10.83,bn_v5_pm_pro13,gokxsfsr3@dftstat.com,okx_v5_test2,gOKXTFMMTEST1,NaN,内部
5,NaN,cfdc_dcpro13,ETH,420.00,663.34,bn_v5_pm_pro9,boshu_bntest4@dftstat.com,okx_v5_test7,okzyeth05,NaN,内部
6,NaN,cfdc_dcpro14,BTC,20.00,10.00,bn_v5_pm_pro17,bloqbtcrndlcxa_virtual@qsbr0fhxmanagedsub.com,okx_v5_test46,BLOQBTCRNDLCXA,NaN,托管
7,NaN,cfdc_dcpro15,USDT,1371748.00,1200000.00,bn_v5_pm_pro3,boshu_bntest18@dftstat.com,okx_v5_test47,okzyusdt11,NaN,内部
8,NaN,cfdc_dcpro16,USDT,1697287.00,1600000.00,bn_v5_pm_pro4,boshu_bntest20@dftstat.com,okx_v5_test48,okzyusdt12,NaN,内部
9,NaN,cfdc_dcpro17,USDT,1689820.00,1618473.00,bn_v5_pm_pro25,binancetfmmtest21@dftstat.com,okx_v5_test49,okzyusdt13,NaN,内部
10,NaN,cfdc_dcpro18,ETH,250.00,391.09,bn_v5_pm_pro18,digifinex_virtual@vzorp3xnmanag,okx_v5_test10,eth231206,NaN,托管
11,NaN,cfdc_dcpro19,ETH,200.00,363.84,bn_v5_pm_pro2,digifinexbtc_virtual@o4ooi44pmanagedsub.com,okx_v5_test6,oketh0109,NaN,托管
12,NaN,cfdc_dcpro2,USDT,1000000.00,1000000.00,bn_v5_pm_pro6,gosfsrmanual2@dftstat.com,okx_v5_test36,OKZYUSDT03,NaN,内部
13,NaN,cfdc_dcpro20,BTC,11.00,15.15,bn_v5_pm_pro28,fuxi1229_virtual@1ib0gs69managedsub.com,okx_v5_test11,okbtc0117,NaN,托管
14,NaN,cfdc_dcpro21,BTC,12.00,12.00,bn_v5_pm_pro29,sausdt0805_virtual@6ifg29vsmanagedsub.com,okx_v5_test20,ranxusdt0331,NaN,托管
15,NaN,cfdc_dcpro22,ETH,682.45,710.00,bn_v5_pm_pro26,binancetfmmtest29@dftstat.com,okx_v5_test29,OKZYETH09,NaN,内部
16,NaN,cfdc_dcpro24,BTC,8.00,34.96,bn_v5_pm_pro19,binancetfmmtest35@dftstat.com,okx_v5_test22,okzybtc03,NaN,内部
17,NaN,cfdc_dcpro25,ETH,200.00,321.74,bn_v5_pm_pro34,bncf01ran20251130_virtual@bjfkmrxumanagedsub.com,okx_v5_test31,cf01ran20241229,NaN,托管
18,NaN,cfdc_dcpro26,BTC,10.00,14.00,bn_v5_pm_pro35,binancetfmmtest44@dftstat.com,okx_v5_test5,okzybtc04,NaN,内部
19,NaN,cfdc_dcpro27,ETH,120.00,232.56,bn_v5_pm_pro36,binancetfmmtest42@dftstat.com,okx_v5_test23,okzyeth01,NaN,内部
20,NaN,cfdc_dcpro28,ETH,200.00,400.00,bn_v5_pm_pro37,eth0110_virtual@bsdgwecjmanagedsub.com,okex5_v4_maker_cross_test8,eth0110,NaN,托管
21,NaN,cfdc_dcpro29,ETH,120.00,181.06,bn_v5_pm_pro38,BINANCETFMMTEST9@dftstat.com,okx_v5_test28,okzyeth04,NaN,内部
22,NaN,cfdc_dcpro3,USDT,1150000.00,2200000.00,bn_v5_pm_pro8,boshu_bntest8@dftstat.com,okx_v5_test37,okzyusdt04,NaN,内部
23,NaN,cfdc_dcpro30,USDT,332357.00,332357.00,bn_v5_pm_pro14,bnckusdt20251219_virtual@6k8wet1dmanagedsub.com,okx_v5_test51,okckusdt20251219,NaN,托管
24,NaN,cfdc_dcpro31,BTC,5.00,5.00,bn_v5_pm_pro39,bncfb720251209_virtual@wcr4jedjmanagedsub.com,okx_v5_test52,okxcfb720251209,NaN,托管
25,NaN,cfdc_dcpro32,ETH,200.00,300.00,bn_v5_pm_pro40,sausdt1014_virtual@sopuwohkmanagedsub.com,okx_v5_test33,cfshi20250110,NaN,托管
26,NaN,cfdc_dcpro33,BTC,6.00,7.00,bn_v5_pm_pro41,btc0110_virtual@ddmo1lwgmanagedsub.com,okx_v5_test9,btc0110,NaN,托管
27,NaN,cfdc_dcpro34,BTC,3.13,3.13,bn_v5_pm_pro42,bnckbtc20251219_virtual@joa1ndonmanagedsub.com,okx_v5_test19,okckbtc20251219,NaN,托管
28,NaN,cfdc_dcpro35,BTC,6.00,16.00,bn_v5_pm_pro44,bndellecodbtc5012026_virtual@g5pxufupmanagedsu...,okx_v5_test53,DellecodBTC05012026,NaN,托管
29,NaN,cfdc_dcpro36,BTC,4.00,4.00,bn_v5_pm_pro45,bncheungbtc0107_virtual@75v7t1tkmanagedsub.com,okx_v5_test13,cheungbtc1110,NaN,托管
30,NaN,cfdc_dcpro38,BTC,15.00,15.00,bn_v5_pm_pro46,bloqbtcrndlcxa2_virtual@v9h5b6ntmanagedsub.com,okx_v5_test55,BloqBTCRndlCXA2,NaN,托管
31,NaN,cfdc_dcpro4,USDT,1200000.00,1500000.00,bn_v5_pm_pro16,gOKXSFSR2@dftstat.com,okx_v5_test38,OKZYUSDT05,NaN,内部
32,NaN,cfdc_dcpro5,USDT,253380.00,289520.00,bn_v5_pm_pro20,boshu_bntest13@dftstat.com,okx_v5_test39,okcfcf01,NaN,内部
33,NaN,cfdc_dcpro6,BTC,10.00,13.51,bn_v5_pm_pro21,cf04ran20250214_virtual@ewmiw03nmanagedsub.com,okx_v5_test32,cf03ran20241230,NaN,托管
34,NaN,cfdc_dcpro7,USDT,600000.00,1750000.00,bn_v5_pm_pro22,bn61btc@dftstat.com,okx_v5_test41,okzyusdt06,NaN,内部
35,NaN,cfdc_dcpro8,USDT,670000.00,1366511.00,bn_v5_pm_pro1,binancetfmmtest51@dftstat.com,okx_v5_test42,okzyusdt07,NaN,内部
36,NaN,cfdc_dcpro9,USDT,939536.35,1579219.47,bn_v5_pm_pro24,boshu_bncf01@dftstat.com,okx_v5_test43,okzyusdt08,NaN,内部

In [5]:
env_info1 = pd.DataFrame(columns=['control', 'accountEquity', 'actualEquity','accountMaintMargin','quoteAmount', 'uniMMR'])
for j in  range(len(dc_name)):
    control = dc_name.loc[j, 'OKX环境']
    print(control)
    symbol = 'BTCUSDT'
    url = f"https://mmadmin.digifinex.org/api/cf_arbitrage/{symbol}"
    querystring = {"env":control}
    json = verfied_session.request("GET", url, cookies = verfied_cookies, params=querystring).json()
    if  json['data'] != None:
        data =json['data']
        account = data['detail']['account']
        accountEquity = float(account['accountEquity'])
        actualEquity = float(account['actualEquity'])
        quoteAmount = float(account['quoteAmount'])
        accountInitialMargin  = float(account['accountInitialMargin'])
        accountMaintMargin= float(account['accountMaintMargin'])
        rest_margin = actualEquity - accountInitialMargin
        uniMMR = float(account['uniMMR'])
    env_info1.loc[env_info1.shape[0]] = [control, accountEquity,actualEquity,accountMaintMargin, quoteAmount, uniMMR]
env_info1=env_info1[['control', 'accountEquity','accountMaintMargin', 'uniMMR']]
env_info1.columns=['OKX环境', 'okx_accountEquity', 'okx_accountMaintMargin', 'okx_uniMMR']
env_info1

bybit5_v5_by3
okx_v5_test12
okx_v5_test44
okx_v5_test45
okx_v5_test2
okx_v5_test7
okx_v5_test46
okx_v5_test47
okx_v5_test48
okx_v5_test49
okx_v5_test10
okx_v5_test6
okx_v5_test36
okx_v5_test11
okx_v5_test20
okx_v5_test29
okx_v5_test22
okx_v5_test31
okx_v5_test5
okx_v5_test23
okex5_v4_maker_cross_test8
okx_v5_test28
okx_v5_test37
okx_v5_test51
okx_v5_test52
okx_v5_test33
okx_v5_test9
okx_v5_test19
okx_v5_test53
okx_v5_test13
okx_v5_test55
okx_v5_test38
okx_v5_test39
okx_v5_test32
okx_v5_test41
okx_v5_test42
okx_v5_test43

,OKX环境,okx_accountEquity,okx_accountMaintMargin,okx_uniMMR
0,bybit5_v5_by3,516997.90,26070.63,0.06
1,okx_v5_test12,583536.02,8065.30,69.80
2,okx_v5_test44,366289.24,7881.00,44.46
3,okx_v5_test45,335901.90,6684.73,47.19
4,okx_v5_test2,621337.20,13860.97,41.79
5,okx_v5_test7,1233250.17,33488.28,34.94
6,okx_v5_test46,1476720.05,20218.97,70.59
7,okx_v5_test47,1375890.53,29774.67,44.67
8,okx_v5_test48,1809399.58,37998.33,46.26
9,okx_v5_test49,1100151.04,13099.39,80.48
10,okx_v5_test10,705303.96,11854.67,54.84
11,okx_v5_test6,513192.47,5738.20,85.15
12,okx_v5_test36,1279087.73,25455.52,48.25
13,okx_v5_test11,942853.19,17499.95,51.60
14,okx_v5_test20,863641.65,24642.16,33.16
15,okx_v5_test29,1537239.25,27804.22,52.90
16,okx_v5_test22,1780955.56,37553.64,44.80
17,okx_v5_test31,544561.69,12602.05,41.00
18,okx_v5_test5,785429.91,15334.49,47.64
19,okx_v5_test23,427215.44,10086.34,38.95
20,okex5_v4_maker_cross_test8,593326.66,10781.83,51.64
21,okx_v5_test28,451896.04,8594.63,48.26
22,okx_v5_test37,1452036.35,52750.55,26.46
23,okx_v5_test51,409238.61,2680.77,146.36
24,okx_v5_test52,322317.91,10635.63,28.19
25,okx_v5_test33,540088.30,15927.16,31.19
26,okx_v5_test9,501768.59,13189.36,35.23
27,okx_v5_test19,223415.99,4728.90,43.79
28,okx_v5_test53,901193.71,13255.47,64.07
29,okx_v5_test13,336808.48,2506.54,122.66
30,okx_v5_test55,1137522.46,27195.05,40.00
31,okx_v5_test38,1417648.89,45524.25,27.47
32,okx_v5_test39,321471.39,4798.85,63.06
33,okx_v5_test32,907790.70,19129.93,44.79
34,okx_v5_test41,1313101.54,15561.87,81.67
35,okx_v5_test42,1035442.72,13610.08,73.34
36,okx_v5_test43,1448512.80,11769.83,119.31

In [6]:
# verfied_session1, verfied_cookies1 = login(prefix='mmadminjp3')
env_info2 = pd.DataFrame(columns=['control', 'accountEquity', 'actualEquity','accountMaintMargin','quoteAmount', 'uniMMR'])
for j in  range(len(dc_name)):
    control = dc_name.loc[j, 'Binance环境']
    print(control)
    symbol = 'BTCUSDT'
    url = f"https://mmadminjp3.digifinex.org/api/cf_arbitrage/{symbol}"
    querystring = {"env":control}
    json = verfied_session1.request("GET", url, cookies = verfied_cookies1, params=querystring).json()
    if  json['data'] != None:
        data =json['data']
        account = data['detail']['account']
        accountEquity = float(account['accountEquity'])
        actualEquity = float(account['actualEquity'])
        quoteAmount = float(account['quoteAmount'])
        accountInitialMargin  = float(account['accountInitialMargin'])
        accountMaintMargin= float(account['accountMaintMargin'])
        rest_margin = actualEquity - accountInitialMargin
        uniMMR = float(account['uniMMR'])
    env_info2.loc[env_info2.shape[0]] = [control, accountEquity,actualEquity,accountMaintMargin, quoteAmount, uniMMR]
env_info2=env_info2[['control', 'accountEquity','accountMaintMargin', 'uniMMR']]
env_info2.columns=['Binance环境', 'binance_accountEquity', 'binance_accountMaintMargin', 'binance_uniMMR']
env_info2

bn_v5_pm_pro43
bn_v5_pm_pro5
bn_v5_pm_pro15
bn_v5_pm_pro7
bn_v5_pm_pro13
bn_v5_pm_pro9
bn_v5_pm_pro17
bn_v5_pm_pro3
bn_v5_pm_pro4
bn_v5_pm_pro25
bn_v5_pm_pro18
bn_v5_pm_pro2
bn_v5_pm_pro6
bn_v5_pm_pro28
bn_v5_pm_pro29
bn_v5_pm_pro26
bn_v5_pm_pro19
bn_v5_pm_pro34
bn_v5_pm_pro35
bn_v5_pm_pro36
bn_v5_pm_pro37
bn_v5_pm_pro38
bn_v5_pm_pro8
bn_v5_pm_pro14
bn_v5_pm_pro39
bn_v5_pm_pro40
bn_v5_pm_pro41
bn_v5_pm_pro42
bn_v5_pm_pro44
bn_v5_pm_pro45
bn_v5_pm_pro46
bn_v5_pm_pro16
bn_v5_pm_pro20
bn_v5_pm_pro21
bn_v5_pm_pro22
bn_v5_pm_pro1
bn_v5_pm_pro24

,Binance环境,binance_accountEquity,binance_accountMaintMargin,binance_uniMMR
0,bn_v5_pm_pro43,450811.37,23992.13,18.79
1,bn_v5_pm_pro5,430307.93,14640.38,29.39
2,bn_v5_pm_pro15,273405.01,18683.74,14.63
3,bn_v5_pm_pro7,310906.71,17037.69,18.25
4,bn_v5_pm_pro13,466764.98,15712.74,29.71
5,bn_v5_pm_pro9,813334.80,56901.63,14.29
6,bn_v5_pm_pro17,506139.06,31230.25,16.21
7,bn_v5_pm_pro3,1202227.80,41196.77,29.18
8,bn_v5_pm_pro4,1502910.12,60246.44,24.95
9,bn_v5_pm_pro25,1230546.44,44343.78,27.75
10,bn_v5_pm_pro18,500105.42,12446.99,40.18
11,bn_v5_pm_pro2,468881.23,21143.66,22.18
12,bn_v5_pm_pro6,750739.41,30642.26,24.50
13,bn_v5_pm_pro28,732521.13,20943.12,34.98
14,bn_v5_pm_pro29,676731.16,16694.81,40.54
15,bn_v5_pm_pro26,1124814.13,24257.16,46.37
16,bn_v5_pm_pro19,950640.31,54384.69,17.48
17,bn_v5_pm_pro34,432769.01,12458.50,34.74
18,bn_v5_pm_pro35,751216.53,17210.28,43.65
19,bn_v5_pm_pro36,232695.33,10478.50,22.21
20,bn_v5_pm_pro37,547416.24,14335.67,38.19
21,bn_v5_pm_pro38,352353.96,6429.28,54.80
22,bn_v5_pm_pro8,771907.81,67743.13,11.39
23,bn_v5_pm_pro14,259475.73,5249.88,49.43
24,bn_v5_pm_pro39,321321.53,7171.87,44.80
25,bn_v5_pm_pro40,413223.12,15558.11,26.56
26,bn_v5_pm_pro41,327574.86,15129.26,21.65
27,bn_v5_pm_pro42,177280.14,2713.70,65.33
28,bn_v5_pm_pro44,508349.57,8911.62,57.04
29,bn_v5_pm_pro45,99587.09,1276.24,78.03
30,bn_v5_pm_pro46,785358.43,17637.42,44.53
31,bn_v5_pm_pro16,1286861.94,51759.40,24.86
32,bn_v5_pm_pro20,277178.77,8092.43,34.25
33,bn_v5_pm_pro21,602537.92,22461.85,26.82
34,bn_v5_pm_pro22,766265.32,26450.92,28.97
35,bn_v5_pm_pro1,1032091.44,31834.10,32.42
36,bn_v5_pm_pro24,893128.35,26203.07,34.08

In [7]:
all_data = pd.merge(dc_name, env_info1, how='left', left_on='OKX环境',  right_on='OKX环境')
all_data = pd.merge(all_data, env_info2, how='left', left_on='Binance环境',  right_on='Binance环境')
all_data['total_equity'] = all_data['okx_accountEquity'] + all_data['binance_accountEquity']
all_data['mean'] = all_data['total_equity']/2
all_data['transfer_equity'] = all_data['okx_accountEquity']-all_data['mean']
all_data['pre_uniMMR'] = all_data['mean'] /all_data['okx_accountMaintMargin'] 
all_data['diff_ratio'] = (all_data['okx_accountEquity'] -all_data['mean'] ) /all_data['mean']
all_data['okx_mark'] = all_data['OKX环境'].apply(lambda x: x.split('_')[-1])
show_column = ['跨所环境', '本金', 'Binance本金', 'OKX本金', 'Binance环境', 'Binance账户名', 'OKX环境',
       'OKX账户名', '类型', 'okx_accountEquity',
       'okx_uniMMR', 'binance_accountEquity',
       'binance_uniMMR', 'total_equity', 'transfer_equity','diff_ratio']
all_data = all_data[show_column]
btc_okx = fetch_okx_last_price("BTC")
eth_okx = fetch_okx_last_price("ETH")

all_data["OKX_BTCUSDT_Price"] = btc_okx
all_data["OKX_ETHUSDT_Price"] = eth_okx

all_data["final_transfer"] = np.select(
    [
        all_data["本金"].eq("BTC"),
        all_data["本金"].eq("ETH"),
        all_data["本金"].eq("USDT"),
    ],
    [
        all_data["transfer_equity"] / all_data["OKX_BTCUSDT_Price"],
        all_data["transfer_equity"] / all_data["OKX_ETHUSDT_Price"],
        all_data["transfer_equity"],
    ],
    default=np.nan,  # 其他币种先留空
)

all_data['abs_diff_ratio'] = all_data['diff_ratio'].abs()
all_data.sort_values('abs_diff_ratio',ascending=False)

,跨所环境,本金,Binance本金,OKX本金,Binance环境,Binance账户名,OKX环境,OKX账户名,类型,okx_accountEquity,okx_uniMMR,binance_accountEquity,binance_uniMMR,total_equity,transfer_equity,diff_ratio,OKX_BTCUSDT_Price,OKX_ETHUSDT_Price,final_transfer,abs_diff_ratio
29,cfdc_dcpro36,BTC,4.00,4.00,bn_v5_pm_pro45,bncheungbtc0107_virtual@75v7t1tkmanagedsub.com,okx_v5_test13,cheungbtc1110,托管,336808.48,122.66,99587.09,78.03,436395.57,118610.69,0.54,63780.90,1859.99,1.86,0.54
6,cfdc_dcpro14,BTC,20.00,10.00,bn_v5_pm_pro17,bloqbtcrndlcxa_virtual@qsbr0fhxmanagedsub.com,okx_v5_test46,BLOQBTCRNDLCXA,托管,1476720.05,70.59,506139.06,16.21,1982859.11,485290.50,0.49,63780.90,1859.99,7.61,0.49
22,cfdc_dcpro3,USDT,1150000.00,2200000.00,bn_v5_pm_pro8,boshu_bntest8@dftstat.com,okx_v5_test37,okzyusdt04,内部,1452036.35,26.46,771907.81,11.39,2223944.15,340064.27,0.31,63780.90,1859.99,340064.27,0.31
16,cfdc_dcpro24,BTC,8.00,34.96,bn_v5_pm_pro19,binancetfmmtest35@dftstat.com,okx_v5_test22,okzybtc03,内部,1780955.56,44.80,950640.31,17.48,2731595.88,415157.63,0.30,63780.90,1859.99,6.51,0.30
19,cfdc_dcpro27,ETH,120.00,232.56,bn_v5_pm_pro36,binancetfmmtest42@dftstat.com,okx_v5_test23,okzyeth01,内部,427215.44,38.95,232695.33,22.21,659910.77,97260.05,0.29,63780.90,1859.99,52.29,0.29
28,cfdc_dcpro35,BTC,6.00,16.00,bn_v5_pm_pro44,bndellecodbtc5012026_virtual@g5pxufupmanagedsu...,okx_v5_test53,DellecodBTC05012026,托管,901193.71,64.07,508349.57,57.04,1409543.28,196422.07,0.28,63780.90,1859.99,3.08,0.28
34,cfdc_dcpro7,USDT,600000.00,1750000.00,bn_v5_pm_pro22,bn61btc@dftstat.com,okx_v5_test41,okzyusdt06,内部,1313101.54,81.67,766265.32,28.97,2079366.87,273418.11,0.26,63780.90,1859.99,273418.11,0.26
12,cfdc_dcpro2,USDT,1000000.00,1000000.00,bn_v5_pm_pro6,gosfsrmanual2@dftstat.com,okx_v5_test36,OKZYUSDT03,内部,1279087.73,48.25,750739.41,24.50,2029827.14,264174.16,0.26,63780.90,1859.99,264174.16,0.26
36,cfdc_dcpro9,USDT,939536.35,1579219.47,bn_v5_pm_pro24,boshu_bncf01@dftstat.com,okx_v5_test43,okzyusdt08,内部,1448512.80,119.31,893128.35,34.08,2341641.14,277692.23,0.24,63780.90,1859.99,277692.23,0.24
23,cfdc_dcpro30,USDT,332357.00,332357.00,bn_v5_pm_pro14,bnckusdt20251219_virtual@6k8wet1dmanagedsub.com,okx_v5_test51,okckusdt20251219,托管,409238.61,146.36,259475.73,49.43,668714.34,74881.44,0.22,63780.90,1859.99,74881.44,0.22
26,cfdc_dcpro33,BTC,6.00,7.00,bn_v5_pm_pro41,btc0110_virtual@ddmo1lwgmanagedsub.com,okx_v5_test9,btc0110,托管,501768.59,35.23,327574.86,21.65,829343.45,87096.86,0.21,63780.90,1859.99,1.37,0.21
5,cfdc_dcpro13,ETH,420.00,663.34,bn_v5_pm_pro9,boshu_bntest4@dftstat.com,okx_v5_test7,okzyeth05,内部,1233250.17,34.94,813334.80,14.29,2046584.97,209957.68,0.21,63780.90,1859.99,112.88,0.21
33,cfdc_dcpro6,BTC,10.00,13.51,bn_v5_pm_pro21,cf04ran20250214_virtual@ewmiw03nmanagedsub.com,okx_v5_test32,cf03ran20241230,托管,907790.70,44.79,602537.92,26.82,1510328.61,152626.39,0.20,63780.90,1859.99,2.39,0.20
30,cfdc_dcpro38,BTC,15.00,15.00,bn_v5_pm_pro46,bloqbtcrndlcxa2_virtual@v9h5b6ntmanagedsub.com,okx_v5_test55,BloqBTCRndlCXA2,托管,1137522.46,40.00,785358.43,44.53,1922880.89,176082.02,0.18,63780.90,1859.99,2.76,0.18
10,cfdc_dcpro18,ETH,250.00,391.09,bn_v5_pm_pro18,digifinex_virtual@vzorp3xnmanag,okx_v5_test10,eth231206,托管,705303.96,54.84,500105.42,40.18,1205409.38,102599.27,0.17,63780.90,1859.99,55.16,0.17
15,cfdc_dcpro22,ETH,682.45,710.00,bn_v5_pm_pro26,binancetfmmtest29@dftstat.com,okx_v5_test29,OKZYETH09,内部,1537239.25,52.90,1124814.13,46.37,2662053.38,206212.56,0.15,63780.90,1859.99,110.87,0.15
1,cfdc_dcpro1,USDT,500000.00,500000.00,bn_v5_pm_pro5,binancetfmmtest50@dftstat.com,okx_v5_test12,Okzyusdt02,内部,583536.02,69.80,430307.93,29.39,1013843.95,76614.05,0.15,63780.90,1859.99,76614.05,0.15
2,cfdc_dcpro10,BTC,5.00,5.00,bn_v5_pm_pro15,cf09ran20250423_virtual@n9nik8gxmanagedsub.com,okx_v5_test44,cf09ran20250423okx,托管,366289.24,44.46,273405.01,14.63,639694.26,46442.11,0.15,63780.90,1859.99,0.73,0.15
4,cfdc_dcpro12,BTC,6.00,10.83,bn_v5_pm_pro13,gokxsfsr3@dftstat.com,okx_v5_test2,gOKXTFMMTEST1,内部,621337.20,41.79,466764.98,29.71,1088102.19,77286.11,0.14,63780.90,1859.99,1.21,0.14
25,cfdc_dcpro32,ETH,200.00,300.00,bn_v5_pm_pro40,sausdt1014_virtual@sopuwohkmanagedsub.com,okx_v5_test33,cfshi20250110,托管,540088.30,31.19,413223.12,26.56,953311.42,63432.59,0.13,63780.90,1859.99,34.10,0.13
13,cfdc_dcpro20,BTC,11.00,15.15,bn_v5_pm_pro28,fuxi1229_virtual@1ib0gs69managedsub.com,okx_v5_test11,okbtc0117,托管,942853.19,51.60,732521.13,34.98,1675374.33,105166.03,0.13,63780.90,1859.99,1.65,0.13
21,cfdc_dcpro29,ETH,120.00,181.06,bn_v5_pm_pro38,BINANCETFMMTEST9@dftstat.com,okx_v5_test28,okzyeth04,内部,451896.04,48.26,352353.96,54.80,804250.01,49771.04,0.12,63780.90,1859.99,26.76,0.12
14,cfdc_dcpro21,BTC,12.00,12.00,bn_v5_pm_pro29,sausdt0805_virtual@6ifg29vsmanagedsub.com,okx_v5_test20,ranxusdt0331,托管,863641.65,33.16,676731.16,40.54,1540372.81,93455.25,0.12,63780.90,1859.99,1.47,0.12
27,cfdc_dcpro34,BTC,3.13,3.13,bn_v5_pm_pro42,bnckbtc20251219_virtual@joa1ndonmanagedsub.com,okx_v5_test19,okckbtc20251219,托管,223415.99,43.79,177280.14,65.33,400696.14,23067.92,0.12,63780.90,1859.99,0.36,0.12
17,cfdc_dcpro25,ETH,200.00,321.74,bn_v5_pm_pro34,bncf01ran20251130_virtual@bjfkmrxumanagedsub.com,okx_v5_test31,cf01ran20241229,托管,544561.69,41.00,432769.01,34.74,977330.71,55896.34,0.11,63780.90,1859.99,30.05,0.11
8,cfdc_dcpro16,USDT,1697287.00,1600000.00,bn_v5_pm_pro4,boshu_bntest20@dftstat.com,okx_v5_test48,okzyusdt12,内部,1809399.58,46.26,1502910.12,24.95,3312309.69,153244.73,0.09,63780.90,1859.99,153244.73,0.09
32,cfdc_dcpro5,USDT,253380.00,289520.00,bn_v5_pm_pro20,boshu_bntest13@dftstat.com,okx_v5_test39,okcfcf01,内部,321471.39,63.06,277178.77,34.25,598650.16,22146.31,0.07,63780.90,1859.99,22146.31,0.07
0,cfdc_dcbb1,BTC,7.50,7.50,bn_v5_pm_pro43,ltpbn30012,bybit5_v5_by3,LPbybit644,托管,516997.90,0.06,450811.37,18.79,967809.27,33093.27,0.07,63780.90,1859.99,0.52,0.07
7,cfdc_dcpro15,USDT,1371748.00,1200000.00,bn_v5_pm_pro3,boshu_bntest18@dftstat.com,okx_v5_test47,okzyusdt11,内部,1375890.53,44.67,1202227.80,29.18,2578118.33,86831.37,0.07,63780.90,1859.99,86831.37,0.07
9,cfdc_dcpro17,USDT,1689820.00,1618473.00,bn_v5_pm_pro25,binancetfmmtest21@dftstat.com,okx_v5_test49,okzyusdt13,内部,1100151.04,80.48,1230546.44,27.75,2330697.48,-65197.70,-0.06,63780.90,1859.99,-65197.70,0.06
31,cfdc_dcpro4,USDT,1200000.00,1500000.00,bn_v5_pm_pro16,gOKXSFSR2@dftstat.com,okx_v5_test38,OKZYUSDT05,内部,1417648.89,27.47,1286861.94,24.86,2704510.84,65393.48,0.05,63780.90,1859.99,65393.48,0.05
11,cfdc_dcpro19,ETH,200.00,363.84,bn_v5_pm_pro2,digifinexbtc_virtual@o4ooi44pmanagedsub.com,okx_v5_test6,oketh0109,托管,513192.47,85.15,468881.23,22.18,982073.70,22155.62,0.05,63780.90,1859.99,11.91,0.05
20,cfdc_dcpro28,ETH,200.00,400.00,bn_v5_pm_pro37,eth0110_virtual@bsdgwecjmanagedsub.com,okex5_v4_maker_cross_test8,eth0110,托管,593326.66,51.64,547416.24,38.19,1140742.90,22955.21,0.04,63780.90,1859.99,12.34,0.04
3,cfdc_dcpro11,BTC,3.50,6.50,bn_v5_pm_pro7,cf10ran20250423_virtual@ftleog2vmanagedsub.com,okx_v5_test45,cf10ran20250423okx,托管,335901.90,47.19,310906.71,18.25,646808.61,12497.59,0.04,63780.90,1859.99,0.20,0.04
18,cfdc_dcpro26,BTC,10.00,14.00,bn_v5_pm_pro35,binancetfmmtest44@dftstat.com,okx_v5_test5,okzybtc04,内部,785429.91,47.64,751216.53,43.65,1536646.44,17106.69,0.02,63780.90,1859.99,0.27,0.02
35,cfdc_dcpro8,USDT,670000.00,1366511.00,bn_v5_pm_pro1,binancetfmmtest51@dftstat.com,okx_v5_test42,okzyusdt07,内部,1035442.72,73.34,1032091.44,32.42,2067534.16,1675.64,0.00,63780.90,1859.99,1675.64,0.00
24,cfdc_dcpro31,BTC,5.00,5.00,bn_v5_pm_pro39,bncfb720251209_virtual@wcr4jedjmanagedsub.com,okx_v5_test52,okxcfb720251209,托管,322317.91,28.19,321321.53,44.80,643639.44,498.19,0.00,63780.90,1859.99,0.01,0.00

In [8]:
import numpy as np
import pandas as pd

imbalance_threshold = 0.25

# ===== 仅用于打印的数量格式：取绝对值；USDT -> xx万，BTC/ETH -> 0.01 =====
ft_abs = all_data["final_transfer"].astype(float).abs()

final_transfer_str = np.where(
    all_data["本金"].eq("USDT"),
    (ft_abs / 10_000).round(0).astype("Int64").astype(str) + "万",
    ft_abs.round(2).map(lambda x: f"{x:.2f}")
)
final_transfer_str = pd.Series(final_transfer_str, index=all_data.index)

# USDT 不加“个”
unit = pd.Series(np.where(all_data["本金"].eq("USDT"), "", "个"), index=all_data.index)

# ===== 过滤：托管 + |diff_ratio|>0.1 =====
need = (all_data["类型"].eq("托管")) & (all_data["diff_ratio"].abs() >imbalance_threshold)

# ===== 关键：按 |diff_ratio| 从大到小（你没有 abs_ratio，就用这个）=====
idx_sorted = all_data.loc[need].assign(abs_ratio=all_data.loc[need, "diff_ratio"].abs()) \
    .sort_values("abs_ratio", ascending=False).index

# ===== BN -> OKX (diff_ratio < 0)，保持 |diff_ratio| 降序 =====
idx_bn_to_okx = idx_sorted[all_data.loc[idx_sorted, "diff_ratio"] < 0]
lines_bn_to_okx = (
    "从BN账户" + all_data.loc[idx_bn_to_okx, "Binance账户名"].astype(str)
    + "转 " + final_transfer_str.loc[idx_bn_to_okx] + unit.loc[idx_bn_to_okx] + " " + all_data.loc[idx_bn_to_okx, "本金"].astype(str)
    + "到OKX账户" + all_data.loc[idx_bn_to_okx, "OKX账户名"].astype(str)
    + " （跨所环境为" + all_data.loc[idx_bn_to_okx, "跨所环境"].astype(str)
    + "，BN环境为" + all_data.loc[idx_bn_to_okx, "Binance环境"].astype(str)
    + "，OKX环境为" + all_data.loc[idx_bn_to_okx, "OKX环境"].astype(str) + "）"
).tolist()

# ===== OKX -> BN (diff_ratio > 0)，保持 |diff_ratio| 降序 =====
idx_okx_to_bn = idx_sorted[all_data.loc[idx_sorted, "diff_ratio"] > 0]
lines_okx_to_bn = (
    "从OKX账户" + all_data.loc[idx_okx_to_bn, "OKX账户名"].astype(str)
    + "转 " + final_transfer_str.loc[idx_okx_to_bn] + unit.loc[idx_okx_to_bn] + " " + all_data.loc[idx_okx_to_bn, "本金"].astype(str)
    + "到BN账户" + all_data.loc[idx_okx_to_bn, "Binance账户名"].astype(str)
    + " （跨所环境为" + all_data.loc[idx_okx_to_bn, "跨所环境"].astype(str)
    + "，BN环境为" + all_data.loc[idx_okx_to_bn, "Binance环境"].astype(str)
    + "，OKX环境为" + all_data.loc[idx_okx_to_bn, "OKX环境"].astype(str) + "）"
).tolist()

# ===== 分组打印：每行空一行 =====
print("BN到OKX")
for s in lines_bn_to_okx:
    print(s)
    print()

print("OKX到BN")
for s in lines_okx_to_bn:
    print(s)
    print()

BN到OKX
OKX到BN
从OKX账户cheungbtc1110转 1.86个 BTC到BN账户bncheungbtc0107_virtual@75v7t1tkmanagedsub.com （跨所环境为cfdc_dcpro36，BN环境为bn_v5_pm_pro45，OKX环境为okx_v5_test13）

从OKX账户BLOQBTCRNDLCXA转 7.61个 BTC到BN账户bloqbtcrndlcxa_virtual@qsbr0fhxmanagedsub.com （跨所环境为cfdc_dcpro14，BN环境为bn_v5_pm_pro17，OKX环境为okx_v5_test46）

从OKX账户DellecodBTC05012026转 3.08个 BTC到BN账户bndellecodbtc5012026_virtual@g5pxufupmanagedsub.com （跨所环境为cfdc_dcpro35，BN环境为bn_v5_pm_pro44，OKX环境为okx_v5_test53）

In [9]:
# ===== 过滤：内部 + |diff_ratio|>0.1 =====

imbalance_threshold = 0.25
need = (all_data["类型"].eq("内部")) & (all_data["diff_ratio"].abs() > imbalance_threshold)

# ===== 数量展示：取绝对值；USDT->万，BTC/ETH->0.01 =====
ft_abs = all_data["final_transfer"].astype(float).abs()

final_transfer_str = np.where(
    all_data["本金"].eq("USDT"),
    (ft_abs / 10_000).round(0).astype("Int64").astype(str) + "万",   # e.g. 144000 -> 14万
    ft_abs.round(2).map(lambda x: f"{x:.2f}")                      # BTC/ETH -> 0.01
)
final_transfer_str = pd.Series(final_transfer_str, index=all_data.index)

# ===== 两个方向 =====
m_okx_to_bn = need & (all_data["diff_ratio"] > 0)   # OKX -> BN
m_bn_to_okx = need & (all_data["diff_ratio"] < 0)   # BN -> OKX
env_pair_str = (
    "("
    + all_data["Binance环境"].astype(str)
    + " + "
    + all_data["OKX环境"].astype(str)
    + ")"
)
# ===== OKX -> BN =====
lines_okx_to_bn = (
    "从内部跨所账户组" + all_data.loc[m_okx_to_bn, "跨所环境"].astype(str)
    + env_pair_str.loc[m_okx_to_bn]
    + "的OKX账户" + all_data.loc[m_okx_to_bn, "OKX账户名"].astype(str)
    + "的funding账户提走 " + final_transfer_str.loc[m_okx_to_bn] + " " + all_data.loc[m_okx_to_bn, "本金"].astype(str)
    + ", 转入Binance账户" + all_data.loc[m_okx_to_bn, "Binance账户名"].astype(str)
    + "的现货账户中。"
).tolist()

# ===== BN -> OKX =====
lines_bn_to_okx = (
    "从内部跨所账户组" + all_data.loc[m_bn_to_okx, "跨所环境"].astype(str)
    + env_pair_str.loc[m_bn_to_okx]
    + "的Binance账户" + all_data.loc[m_bn_to_okx, "Binance账户名"].astype(str)
    + "的现货账户提走 " + final_transfer_str.loc[m_bn_to_okx] + " " + all_data.loc[m_bn_to_okx, "本金"].astype(str)
    + ", 转入OKX账户" + all_data.loc[m_bn_to_okx, "OKX账户名"].astype(str)
    + "的funding账户中。"
).tolist()

# ===== 打印整段申请模板 =====
print("Mark您好，因CF跨所套利策略账户资金不平衡，现申请在okx和binance之间转账：\n")

print("从OKX 转到 Binance：（如果有）")
if lines_okx_to_bn:
    for s in lines_okx_to_bn:
        print(s)
        print()
else:
    print("（无）\n")

print("从Binance转到 OKX：(如果有）")
if lines_bn_to_okx:
    for s in lines_bn_to_okx:
        print(s)
        print()
else:
    print("（无）\n")

print("\n资金已经都在两个交易所对应的资金账户了，谢谢Mark")

Mark您好，因CF跨所套利策略账户资金不平衡，现申请在okx和binance之间转账：

从OKX 转到 Binance：（如果有）
从内部跨所账户组cfdc_dcpro2(bn_v5_pm_pro6 + okx_v5_test36)的OKX账户OKZYUSDT03的funding账户提走 26万 USDT, 转入Binance账户gosfsrmanual2@dftstat.com的现货账户中。

从内部跨所账户组cfdc_dcpro24(bn_v5_pm_pro19 + okx_v5_test22)的OKX账户okzybtc03的funding账户提走 6.51 BTC, 转入Binance账户binancetfmmtest35@dftstat.com的现货账户中。

从内部跨所账户组cfdc_dcpro27(bn_v5_pm_pro36 + okx_v5_test23)的OKX账户okzyeth01的funding账户提走 52.29 ETH, 转入Binance账户binancetfmmtest42@dftstat.com的现货账户中。

从内部跨所账户组cfdc_dcpro3(bn_v5_pm_pro8 + okx_v5_test37)的OKX账户okzyusdt04的funding账户提走 34万 USDT, 转入Binance账户boshu_bntest8@dftstat.com的现货账户中。

从内部跨所账户组cfdc_dcpro7(bn_v5_pm_pro22 + okx_v5_test41)的OKX账户okzyusdt06的funding账户提走 27万 USDT, 转入Binance账户bn61btc@dftstat.com的现货账户中。

从Binance转到 OKX：(如果有）
（无）


资金已经都在两个交易所对应的资金账户了，谢谢Mark

In [10]:
all_data[all_data['类型'] =='托管'].sort_values(by = 'diff_ratio', ascending=False)

,跨所环境,本金,Binance本金,OKX本金,Binance环境,Binance账户名,OKX环境,OKX账户名,类型,okx_accountEquity,okx_uniMMR,binance_accountEquity,binance_uniMMR,total_equity,transfer_equity,diff_ratio,OKX_BTCUSDT_Price,OKX_ETHUSDT_Price,final_transfer,abs_diff_ratio
29,cfdc_dcpro36,BTC,4.00,4.00,bn_v5_pm_pro45,bncheungbtc0107_virtual@75v7t1tkmanagedsub.com,okx_v5_test13,cheungbtc1110,托管,336808.48,122.66,99587.09,78.03,436395.57,118610.69,0.54,63780.90,1859.99,1.86,0.54
6,cfdc_dcpro14,BTC,20.00,10.00,bn_v5_pm_pro17,bloqbtcrndlcxa_virtual@qsbr0fhxmanagedsub.com,okx_v5_test46,BLOQBTCRNDLCXA,托管,1476720.05,70.59,506139.06,16.21,1982859.11,485290.50,0.49,63780.90,1859.99,7.61,0.49
28,cfdc_dcpro35,BTC,6.00,16.00,bn_v5_pm_pro44,bndellecodbtc5012026_virtual@g5pxufupmanagedsu...,okx_v5_test53,DellecodBTC05012026,托管,901193.71,64.07,508349.57,57.04,1409543.28,196422.07,0.28,63780.90,1859.99,3.08,0.28
23,cfdc_dcpro30,USDT,332357.00,332357.00,bn_v5_pm_pro14,bnckusdt20251219_virtual@6k8wet1dmanagedsub.com,okx_v5_test51,okckusdt20251219,托管,409238.61,146.36,259475.73,49.43,668714.34,74881.44,0.22,63780.90,1859.99,74881.44,0.22
26,cfdc_dcpro33,BTC,6.00,7.00,bn_v5_pm_pro41,btc0110_virtual@ddmo1lwgmanagedsub.com,okx_v5_test9,btc0110,托管,501768.59,35.23,327574.86,21.65,829343.45,87096.86,0.21,63780.90,1859.99,1.37,0.21
33,cfdc_dcpro6,BTC,10.00,13.51,bn_v5_pm_pro21,cf04ran20250214_virtual@ewmiw03nmanagedsub.com,okx_v5_test32,cf03ran20241230,托管,907790.70,44.79,602537.92,26.82,1510328.61,152626.39,0.20,63780.90,1859.99,2.39,0.20
30,cfdc_dcpro38,BTC,15.00,15.00,bn_v5_pm_pro46,bloqbtcrndlcxa2_virtual@v9h5b6ntmanagedsub.com,okx_v5_test55,BloqBTCRndlCXA2,托管,1137522.46,40.00,785358.43,44.53,1922880.89,176082.02,0.18,63780.90,1859.99,2.76,0.18
10,cfdc_dcpro18,ETH,250.00,391.09,bn_v5_pm_pro18,digifinex_virtual@vzorp3xnmanag,okx_v5_test10,eth231206,托管,705303.96,54.84,500105.42,40.18,1205409.38,102599.27,0.17,63780.90,1859.99,55.16,0.17
2,cfdc_dcpro10,BTC,5.00,5.00,bn_v5_pm_pro15,cf09ran20250423_virtual@n9nik8gxmanagedsub.com,okx_v5_test44,cf09ran20250423okx,托管,366289.24,44.46,273405.01,14.63,639694.26,46442.11,0.15,63780.90,1859.99,0.73,0.15
25,cfdc_dcpro32,ETH,200.00,300.00,bn_v5_pm_pro40,sausdt1014_virtual@sopuwohkmanagedsub.com,okx_v5_test33,cfshi20250110,托管,540088.30,31.19,413223.12,26.56,953311.42,63432.59,0.13,63780.90,1859.99,34.10,0.13
13,cfdc_dcpro20,BTC,11.00,15.15,bn_v5_pm_pro28,fuxi1229_virtual@1ib0gs69managedsub.com,okx_v5_test11,okbtc0117,托管,942853.19,51.60,732521.13,34.98,1675374.33,105166.03,0.13,63780.90,1859.99,1.65,0.13
14,cfdc_dcpro21,BTC,12.00,12.00,bn_v5_pm_pro29,sausdt0805_virtual@6ifg29vsmanagedsub.com,okx_v5_test20,ranxusdt0331,托管,863641.65,33.16,676731.16,40.54,1540372.81,93455.25,0.12,63780.90,1859.99,1.47,0.12
27,cfdc_dcpro34,BTC,3.13,3.13,bn_v5_pm_pro42,bnckbtc20251219_virtual@joa1ndonmanagedsub.com,okx_v5_test19,okckbtc20251219,托管,223415.99,43.79,177280.14,65.33,400696.14,23067.92,0.12,63780.90,1859.99,0.36,0.12
17,cfdc_dcpro25,ETH,200.00,321.74,bn_v5_pm_pro34,bncf01ran20251130_virtual@bjfkmrxumanagedsub.com,okx_v5_test31,cf01ran20241229,托管,544561.69,41.00,432769.01,34.74,977330.71,55896.34,0.11,63780.90,1859.99,30.05,0.11
0,cfdc_dcbb1,BTC,7.50,7.50,bn_v5_pm_pro43,ltpbn30012,bybit5_v5_by3,LPbybit644,托管,516997.90,0.06,450811.37,18.79,967809.27,33093.27,0.07,63780.90,1859.99,0.52,0.07
11,cfdc_dcpro19,ETH,200.00,363.84,bn_v5_pm_pro2,digifinexbtc_virtual@o4ooi44pmanagedsub.com,okx_v5_test6,oketh0109,托管,513192.47,85.15,468881.23,22.18,982073.70,22155.62,0.05,63780.90,1859.99,11.91,0.05
20,cfdc_dcpro28,ETH,200.00,400.00,bn_v5_pm_pro37,eth0110_virtual@bsdgwecjmanagedsub.com,okex5_v4_maker_cross_test8,eth0110,托管,593326.66,51.64,547416.24,38.19,1140742.90,22955.21,0.04,63780.90,1859.99,12.34,0.04
3,cfdc_dcpro11,BTC,3.50,6.50,bn_v5_pm_pro7,cf10ran20250423_virtual@ftleog2vmanagedsub.com,okx_v5_test45,cf10ran20250423okx,托管,335901.90,47.19,310906.71,18.25,646808.61,12497.59,0.04,63780.90,1859.99,0.20,0.04
24,cfdc_dcpro31,BTC,5.00,5.00,bn_v5_pm_pro39,bncfb720251209_virtual@wcr4jedjmanagedsub.com,okx_v5_test52,okxcfb720251209,托管,322317.91,28.19,321321.53,44.80,643639.44,498.19,0.00,63780.90,1859.99,0.01,0.00