In [2]:
from AutoClass import *
import pandas as pd
import json
import requests
import csv
import datetime
from dateutil.relativedelta import relativedelta
import requests
from requests.auth import HTTPBasicAuth
import os
import hmac
import math
import base64
import struct
import hashlib
import time
from contextlib import closing
from zipfile import ZipFile
import pandas as pd
import shutil
from urllib.parse import urlparse

pd.set_option('display.float_format', lambda x: '%.3f' % x)

proxies = {'https':'127.0.0.1:1087', 'http':'127.0.0.1:1087'}

In [3]:
binanceController = AutoParamController("binance3", proxies)
# verfied_session, verfied_cookies = login(prefix='mmadminjp')
binanceController.login()
binanceController.initSymbolsList()

# okxController = AutoParamController("okx", proxies)
# # verfied_session, verfied_cookies = login(prefix='mmadminjp')
# okxController.login()
# okxController.initSymbolsList()

ray_xu 878977
<Response [200]> <html><head><script>location.reload()</script></head></html>
 {'Server': 'openresty', 'Date': 'Tue, 03 Mar 2026 10:05:40 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Set-Cookie': 'auth=1772553940:ray_xu:KapsCH9ydoEKo5E00iomoKMboag=; Expires=Tue, 03-Mar-26 16:05:40 GMT; Max-Age=21600; Path=/; HttpOnly', 'Expires': 'Tue, 03 Mar 2026 10:05:39 GMT', 'Cache-Control': 'no-cache', 'X-Frame-Options': 'sameorigin', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000', 'Content-Encoding': 'gzip'}
ray_xu 210647 https://mmadminjp3.digifinex.org/
<Response [200]>
bn_v5_pm_pro23的symbol_list初始化失败
bn_v5_pm_pro32的symbol_list初始化失败
bn_v5_pm_arbSa的symbol_list初始化失败
bn_v5_pm_arbSa2的symbol_list初始化失败

In [4]:
# 控制台查询剩余的一些现货
# [22, 23, 24, 26]
# target_env = [f'bn_v4_pm_pro{i}' for i in [6, 10, 12, 16, 17, 21, 26, 29, 31]]
target_env = [f'bn_v5_pm_{i}' for i in ['pro5']]
# target_env = [f'bn_v4_pm_test']

symbol_dict = binanceController.tt_symbol_dict
for env, symbol_list in symbol_dict.items():
    if env in target_env:
        querystring = {"env":env}
        print(env)
        for symbol in symbol_list:
            try:
                print(symbol)
                url = f"https://{binanceController.prefix}.digifinex.org/api/cf_arbitrage/{symbol}"
                response = binanceController.verified_session.request("GET", url, cookies = binanceController.verified_cookies, params=querystring)
                response_dict = response.json()

                account_info = response_dict['data']['detail']['account']
    #             print(account_info)
                baseAmount = float(account_info['baseAmount'])
                baseBorrowed = float(account_info['baseBorrowed'])
            
                posAmount = float(response_dict['data']['detail']['pos_list']['pos_amount'])
                localPosAmount = float(response_dict['data']['detail']['pos_list']['local_pos_amount'])
                if (posAmount!=0)|(localPosAmount!=0):
                    print(symbol, posAmount, localAmount)
                else:
                    if baseBorrowed != 0:
                        print(f'{symbol}负债为{baseBorrowed}')
                    if baseAmount < 0:
                        print(f'{symbol}负余额为{baseAmount*cur_spot_price}')
                    pass
#                     update_json = {"change":[{"control":env, "symbol":f"{symbol}", "running":False, "config":{}}]}
#                     print(update_json)
#                     binanceController.updateConfig(update_json)
            
                if 'USDT' in symbol:
                    request_symbol_name = symbol
                else:
                    request_symbol_name = symbol + 'T'
                url = f'https://api.binance.com/api/v3/aggTrades?symbol={request_symbol_name}&limit=1000'
#                 print(requests.get(url, proxies=proxies).json())
                aggTradesDf = pd.DataFrame(requests.get(url, proxies=proxies).json())
                cur_spot_price = float(aggTradesDf.iloc[-1]['p'])
                
#                 print(symbol, baseAmount, cur_spot_price, baseAmount*cur_spot_price, baseBorrowed)
                if baseAmount*cur_spot_price >= 3:
                    print(symbol, baseAmount, cur_spot_price, baseAmount*cur_spot_price)
                if baseBorrowed != 0:
                    print(f'{symbol}负债为{baseBorrowed}')
                if baseAmount < 0:
                    print(f'{symbol}负余额为{baseAmount*cur_spot_price}')
            except Exception as e:
                continue
                print(symbol, e)

bn_v5_pm_pro5
1000CATUSDT
1000CHEEMSUSDT
1000SATSUSDT
1INCHUSDT
1MBABYDOGEUSDT
2ZUSDT
AAVEUSDT
ACHUSDT
ACTUSDT
ADAUSDT
ALGOUSDT
ALICEUSDT
ALTUSDT
APEUSDT
APTUSDT
ARBUSDT
ARUSDT
ATOMUSDT
AUCTIONUSDT
AUSDT
AVAUSDT
AVAXUSDT
AVNTUSDT
AXSUSDT
BABYUSDT
BAKEUSDT
BANANAS31USDT
BANDUSDT
BATUSDT
BCHUSDT
BEAMXUSDT
BELUSDT
BIGTIMEUSDT
BLURUSDT
BMTUSDT
BNBUSDT
BOMEUSDT
BREVUSDT
BROCCOLI714USDT
BTCUSDT
CAKEUSDT
CATIUSDT
CFXUSDT
CHZUSDT
CKBUSDT
COMPUSDT
COTIUSDT
COWUSDT
CRVUSDT
CVCUSDT
DASHUSDT
DEXEUSDT
DFUSDT
DOGEUSDT
DOGSUSDT
DOTUSDT
DUSKUSDT
DYDXUSDT
EDUUSDT
EGLDUSDT
EIGENUSDT
ENAUSDT
ENJUSDT
ENSUSDT
ERAUSDT
ETCUSDT
ETHUSDT
FETUSDT
FFUSDT
FILUSDT
FLMUSDT
FOGOUSDT
FORMUSDT
FORTHUSDT
FRAXUSDT
FXSUSDT
GALAUSDT
GIGGLEUSDT
GLMUSDT
GMTUSDT
GPSUSDT
GTCUSDT
GUNUSDT
HBARUSDT
HEIUSDT
HMSTRUSDT
HUMAUSDT
HYPERUSDT
ICPUSDT
ICXUSDT
IMXUSDT
INITUSDT
INJUSDT
IOSTUSDT
IOTAUSDT
JSTUSDT
JUPUSDT
KAITOUSDT
KDAUSDT
KERNELUSDT
KITEUSDT
KMNOUSDT
LAYERUSDT
LDOUSDT
LINKUSDT
LISTAUSDT
LOKAUSDT
LQTYUSDT
LTCUSDT
LUMIAUSDT
MAGICUSDT
MANAUSDT
MASKUSDT
MAVUSDT
METISUSDT
MEUSDT
MINAUSDT
MIRAUSDT
MKRUSDT
MMTUSDT
MORPHOUSDT
MUBARAKUSDT
NEARUSDT
NEIROUSDT
NEOUSDT
NILUSDT
NOTUSDT
OMUSDT
ONDOUSDT
OPENUSDT
OPUSDT
ORCAUSDT
ORDIUSDT
PARTIUSDT
PAXGUSDT
PENDLEUSDT
PENGUUSDT
PEOPLEUSDT
PIXELUSDT
PLUMEUSDT
PNUTUSDT
PROMUSDT
PROVEUSDT
PUMPUSDT
PUNDIXUSDT
QNTUSDT
QTUMUSDT
REDUSDT
RENDERUSDT
RONINUSDT
RSRUSDT
RUNEUSDT
SAGAUSDT
SANDUSDT
SAPIENUSDT
SCRUSDT
SEIUSDT
SENTUSDT
SFPUSDT
SHELLUSDT
SIGNUSDT
SKYUSDT
SOLUSDT
SOLVUSDT
SOPHUSDT
SPKUSDT
SSVUSDT
STGUSDT
STORJUSDT
STRKUSDT
STXUSDT
SUIUSDT
SUNUSDT
SUPERUSDT
SUSDT
SUSHIUSDT
SYNUSDT
TAOUSDT
THEUSDT
TIAUSDT
TONUSDT
TRBUSDT
TRUMPUSDT
TRXUSDT
TSTUSDT
TURBOUSDT
TUTUSDT
TWTUSDT
UNIUSDT
USDCUSDT
USUALUSDT
VANAUSDT
VANRYUSDT
VETUSDT
VICUSDT
VIRTUALUSDT
VTHOUSDT
WIFUSDT
WLDUSDT
XAIUSDT
XLMUSDT
XPLUSDT
XRPUSDT
XTZUSDT
XVGUSDT
YBUSDT
YFIUSDT
ZECUSDT
ZENUSDT
ZILUSDT
ZKUSDT
ZROUSDT
币安人生USDT

In [40]:
# 清理剩余的一些套利仓位
target_env_list = ['bn_v5_pm_pro5']

# [22, 23, 24, 26]
# [14, 19, 22, 23, 25, 26, 31]
# target_env = total_env_list
target_env = target_env_list
not_symbol_list = ['BNBUSDT']
is_true = False
is_true = True
clean_usdt_value_threshold = 100

symbol_dict = binanceController.tt_symbol_dict
for env, symbol_list in symbol_dict.items():
    if env in target_env:
        querystring = {"env":env}
        print(env)
        for symbol in symbol_list:
            if symbol not in not_symbol_list:
                try:
                    print(symbol)
                    url = f"https://{binanceController.prefix}.digifinex.org/api/cf_arbitrage/{symbol}"
                    response = binanceController.verified_session.request("GET", url, cookies = binanceController.verified_cookies, params=querystring)
                    response_dict = response.json()

                    account_info = response_dict['data']['detail']['account']
        #             print(account_info)
                    baseAmount = float(account_info['baseAmount'])
                    baseBorrowed = float(account_info['baseBorrowed'])
                    poss = pd.DataFrame(response_dict['data']['detail']['pos_list']['poss'])
                    
                    posAmount = float(response_dict['data']['detail']['pos_list']['pos_amount'])
                    localPosAmount = float(response_dict['data']['detail']['pos_list']['local_pos_amount'])
                    localPosAmountMt = float(response_dict['data']['detail']['pos_list']['local_pos_amount_mt'])
                    localPosAmountTm = float(response_dict['data']['detail']['pos_list']['local_pos_amount_tm'])
                    localPosAmount = localPosAmount+localPosAmountMt+localPosAmountTm

                    

                    
                    open_allowed = bool(response_dict['data']['config']['open_allowed'])

                    if 'USDT' in symbol:
                        request_symbol_name = symbol
                    else:
                        request_symbol_name = symbol + 'T'
                    url = f'https://api.binance.com/api/v3/aggTrades?symbol={request_symbol_name}&limit=1000'
                    aggTradesDf = pd.DataFrame(requests.get(url, proxies=proxies).json())
                    cur_spot_price = float(aggTradesDf.iloc[-1]['p'])
                    if (baseAmount*cur_spot_price <= clean_usdt_value_threshold) & (posAmount>0) & (((posAmount-localPosAmount)*cur_spot_price)<clean_usdt_value_threshold) & (not open_allowed):
                        print(symbol, baseAmount, cur_spot_price, baseAmount*cur_spot_price)
                        if is_true:
                            headers = {
                                "content-type": "application/json"
                            }

                            # 平合约
                            swapOrder ={"type":"swap","side":'closeShort',"amount":str(posAmount)}
                            url = f"https://{binanceController.prefix}.digifinex.org/api/cf_arbitrage/{symbol}/addOrder?env={env}"
                            print(url, swapOrder)
                            response = binanceController.verified_session.request("POST", url,
                                                                              cookies = binanceController.verified_cookies,
                                                                              headers = headers, 
                                                                              data=json.dumps(swapOrder))
                            print(response.status_code)
                            print(response.json())  
                            time.sleep(5)

                            # 重启并关闭
                            update_json = {"change":[{"control":env, "symbol":f"{symbol}", "running":False}]}
                            print(update_json)
                            binanceController.updateConfig(update_json)
                            time.sleep(1)
                            update_json = {"change":[{"control":env, "symbol":f"{symbol}", "running":True,
                                                      "config":{"open_allowed":True, "close_allowed":True}}]}
                            print(update_json)
                            binanceController.updateConfig(update_json)
                            update_json = {"change":[{"control":env, "symbol":f"{symbol}", "running":False}]}
                            print(update_json)
                            binanceController.updateConfig(update_json)
                            time.sleep(2)

                            # 清理环境
                            clear_url = f"https://{binanceController.prefix}.digifinex.org/api/cf_arbitrage/{symbol}/clear?env={env}"
                            response = binanceController.verified_session.request("PUT", clear_url,
                                                                                cookies = binanceController.verified_cookies,
                                                                                headers=headers)
                            print(response.status_code)
                            print(response.json())  
                            time.sleep(1)

                            # 平现货
                            spotOrder ={"type":"spot","side":"sell","amount":str(baseAmount)}
                            url = f"https://{binanceController.prefix}.digifinex.org/api/cf_arbitrage/{symbol}/addOrder?env={env}"
                            print(url, spotOrder)
                            response = binanceController.verified_session.request("POST", url,
                                                             cookies = binanceController.verified_cookies,
                                                             headers = headers, 
                                                             data=json.dumps(spotOrder))
                            print(response.status_code)
                            print(response.json())    
                            time.sleep(1)

                            # 重启再关闭
                            update_json = {"change":[{"control":env, "symbol":f"{symbol}", "running":False}]}
                            print(update_json)
                            binanceController.updateConfig(update_json)
                            time.sleep(1)
                            update_json = {"change":[{"control":env, "symbol":f"{symbol}", "running":True,
                                                      "config":{"open_allowed":True, "close_allowed":True}}]}
                            print(update_json)
                            binanceController.updateConfig(update_json)
                            time.sleep(1)
                            update_json = {"change":[{"control":env, "symbol":f"{symbol}", "running":False}]}
                            print(update_json)
                            binanceController.updateConfig(update_json)
                            time.sleep(1)

                except Exception as e:
#                     print(e)
                    continue

bn_v5_pm_pro26
1000CHEEMSUSDT
1000SATSUSDT
1INCHUSDT
AAVEUSDT
ACTUSDT
ADAUSDT
ALGOUSDT
ALICEUSDT
ALTUSDT
ANIMEUSDT
APEUSDT
APTUSDT
ARBUSDT
ARUSDT
ASRUSDT
ATOMUSDT
AUCTIONUSDT
AUSDT
AVAXUSDT
AXSUSDT
BABYUSDT
BAKEUSDT
BANANAS31USDT
BCHUSDT
BELUSDT
BERAUSDT
BIGTIMEUSDT
BMTUSDT
BNXUSDT
BOMEUSDT
BROCCOLI714USDT
BTCUSD
BTCUSDT
CAKEUSDT
CATIUSDT
CFXUSDT
CHZUSDT
COMBOUSDT
COMPUSDT
COSUSDT
COTIUSDT
COWUSDT
CRVUSDT
DASHUSDT
DEGOUSDT
DEXEUSDT
DFUSDT
DOGEUSDT
DOGSUSDT
DOTUSDT
DUSKUSDT
DYDXUSDT
EGLDUSDT
EIGENUSDT
ENAUSDT
ENSUSDT
EOSUSDT
ETCUSDT
ETHUSDT
FETUSDT
FILUSDT
FIOUSDT
FLMUSDT
FLOWUSDT
FORMUSDT
FORTHUSDT
FUNUSDT
FXSUSDT
GALAUSDT
GMTUSDT
GTCUSDT
GUNUSDT
HBARUSDT
HEIUSDT
HMSTRUSDT
HUMAUSDT
HYPERUSDT
ICPUSDT
ICXUSDT
INITUSDT
INJUSDT
IOSTUSDT
IOTAUSDT
JUPUSDT
KAITOUSDT
KAVAUSDT
KDAUSDT
KERNELUSDT
KMNOUSDT
LAYERUSDT
LDOUSDT
LINAUSDT
LINKUSDT
LISTAUSDT
LOKAUSDT
LQTYUSDT
LTCUSDT
LUMIAUSDT
MAGICUSDT
MANAUSDT
MASKUSDT
MEMEUSDT
METISUSDT
MINAUSDT
MKRUSDT
MUBARAKUSDT
NEARUSDT
NEIROUSDT
NEOUSDT
NILUSDT
NOTUSDT
NXPCUSDT
OMUSDT
ONDOUSDT
OPUSDT
ORCAUSDT
ORDIUSDT
PARTIUSDT
PAXGUSDT
PENDLEUSDT
PENGUUSDT
PEOPLEUSDT
PIXELUSDT
PNUTUSDT
POLUSDT
PROMUSDT
PUMPUSDT
QNTUSDT
QTUMUSDT
RENDERUSDT
RLCUSDT
ROSEUSDT
RSRUSDT
RUNEUSDT
RVNUSDT
SAGAUSDT
SANDUSDT
SCRUSDT
SEIUSDT
SFPUSDT
SHELLUSDT
SIGNUSDT
SOLUSDT
SOLVUSDT
SOPHUSDT
STOUSDT
STRKUSDT
SUIUSDT
SUNUSDT
SUPERUSDT
SUSDT
SUSHIUSDT
SYNUSDT
SYRUPUSDT
TAOUSDT
THETAUSDT
THEUSDT
TIAUSDT
TONUSDT
TRBUSDT
TROYUSDT
TRUMPUSDT
TRUUSDT
TRXUSDT
TSTUSDT
TURBOUSDT
TUTUSDT
TWTUSDT
UNIUSDT
USDCUSDT
VANAUSDT
VANRYUSDT
VETUSDT
VICUSDT
VIRTUALUSDT
WCTUSDT
WIFUSDT
WLDUSDT
XLMUSDT
XPLUSDT
XRPUSDT
XTZUSDT
ZECUSDT
ZENUSDT
ZILUSDT
ZKUSDT

In [59]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
    env = 'bn_v5_pm_pro32'
    # env = 'bn_v5_pm_pro6'
    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'POST',    # GET/POST
        'private': True,    # True/False
        'url': "https://api.binance.com/sapi/v1/portfolio/repay-futures-negative-balance",
        'params':{'from':'MARGIN'}
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    print(response.text)
    print(response.json())

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro32', 'method': 'POST', 'private': True, 'url': 'https://api.binance.com/sapi/v1/portfolio/repay-futures-negative-balance', 'params': {'from': 'MARGIN'}}
{"data":{"msg":"success"},"error":""}

{'data': {'msg': 'success'}, 'error': ''}

In [73]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
#     env = 'bn_v4_pm_pro25'
    env = 'bn_v5_pm_pro26'
    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'POST',    # GET/POST
        'private': True,    # True/False
        'url': "https://api.binance.com/sapi/v1/portfolio/bnb-transfer",
        'params':{"amount":0.00070142, "transferSide":"TO_UM"}
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    print(response.text)
    print(response.json())

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro26', 'method': 'POST', 'private': True, 'url': 'https://api.binance.com/sapi/v1/portfolio/bnb-transfer', 'params': {'amount': 0.00070142, 'transferSide': 'FROM_UM'}}
{"data":{"tranId":345379174933},"error":""}

{'data': {'tranId': 345379174933}, 'error': ''}

In [124]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
#     env = 'bn_v4_pm_pro25'
    env = 'bn_v5_pm_test17'
    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'POST',    # GET/POST
        'private': True,    # True/False
        'url': "https://api.binance.com/sapi/v1/portfolio/bnb-transfer",
        'params':{"amount":0.02453607, "transferSide":"FROM_UM"}
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    print(response.text)
    print(response.json())

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_test17', 'method': 'POST', 'private': True, 'url': 'https://api.binance.com/sapi/v1/portfolio/bnb-transfer', 'params': {'amount': 0.02453607, 'transferSide': 'FROM_UM'}}
{"data":{"tranId":337602160401},"error":""}

{'data': {'tranId': 337602160401}, 'error': ''}

In [43]:
# import requests
# import json

# headers = {
#     'Content-Type': 'application/json'
# }



# if __name__ == '__main__':
# #     env = 'bn_v4_pm_pro25'
#     env = 'bn_v5_pm_arbSa'
#     url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
#     data = {
#         'env':env,
#         'method': 'POST',    # GET/POST
#         'private': True,    # True/False
#         'url': "https://api.binance.com/sapi/v1/asset/transfer",
#         'params':{"type":"MARGIN_MAIN", "asset":"BNB", "amount":105.17189473}
#     }

#     print(f'{url}: {data}')
#     response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
# #     response = requests.post(url, headers=headers, data=json.dumps(data))
#     print(response.text)
#     print(response.json())

In [17]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
    env = 'bn_v5_pm_pro26'
    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'GET',    # GET/POST
        'private': True,    # True/False
        'url': "https://fapi.binance.com/fapi/v3/account",
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    # print(response.text)
    print(response.json())
usdmPositionsDf = pd.DataFrame(response.json()['data']['positions'])
usdmAssetsDf = pd.DataFrame(response.json()['data']['assets'])
# usdmPositionsDf['maintMargin'] = usdmPositionsDf['maintMargin'].astype(float)
# usdmPositionsDf['unrealizedProfit'] = usdmPositionsDf['unrealizedProfit'].astype(float)

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro23', 'method': 'GET', 'private': True, 'url': 'https://fapi.binance.com/fapi/v3/account'}
{'data': {'assets': [{'asset': 'FDUSD', 'availableBalance': '0.00000000', 'crossUnPnl': '0.00000000', 'crossWalletBalance': '0.00000000', 'initialMargin': '0.00000000', 'maintMargin': '0.00000000', 'marginBalance': '0.00000000', 'maxWithdrawAmount': '0.00000000', 'openOrderInitialMargin': '0.00000000', 'positionInitialMargin': '0.00000000', 'unrealizedProfit': '0.00000000', 'updateTime': 0, 'walletBalance': '0.00000000'}, {'asset': 'LDUSDT', 'availableBalance': '0.00000000', 'crossUnPnl': '0.00000000', 'crossWalletBalance': '0.00000000', 'initialMargin': '0.00000000', 'maintMargin': '0.00000000', 'marginBalance': '0.00000000', 'maxWithdrawAmount': '0.00000000', 'openOrderInitialMargin': '0.00000000', 'positionInitialMargin': '0.00000000', 'unrealizedProfit': '0.00000000', 'updateTime': 0, 'walletBalance': '0.00000000'}, {'asset': 'BFUSD', 'availableBalance': '0.00000000', 'crossUnPnl': '0.00000000', 'crossWalletBalance': '0.00000000', 'initialMargin': '0.00000000', 'maintMargin': '0.00000000', 'marginBalance': '0.00000000', 'maxWithdrawAmount': '0.00000000', 'openOrderInitialMargin': '0.00000000', 'positionInitialMargin': '0.00000000', 'unrealizedProfit': '0.00000000', 'updateTime': 0, 'walletBalance': '0.00000000'}, {'asset': 'BNB', 'availableBalance': '0.29513250', 'crossUnPnl': '0.00000000', 'crossWalletBalance': '0.29513250', 'initialMargin': '0.00000000', 'maintMargin': '0.00000000', 'marginBalance': '0.29513250', 'maxWithdrawAmount': '0.29513250', 'openOrderInitialMargin': '0.00000000', 'positionInitialMargin': '0.00000000', 'unrealizedProfit': '0.00000000', 'updateTime': 1768553009156, 'walletBalance': '0.29513250'}, {'asset': 'ETH', 'availableBalance': '0.00000000', 'crossUnPnl': '0.00000000', 'crossWalletBalance': '0.00000000', 'initialMargin': '0.00000000', 'maintMargin': '0.00000000', 'marginBalance': '0.00000000', 'maxWithdrawAmount': '0.00000000', 'openOrderInitialMargin': '0.00000000', 'positionInitialMargin': '0.00000000', 'unrealizedProfit': '0.00000000', 'updateTime': 0, 'walletBalance': '0.00000000'}, {'asset': 'RWUSD', 'availableBalance': '0.00000000', 'crossUnPnl': '0.00000000', 'crossWalletBalance': '0.00000000', 'initialMargin': '0.00000000', 'maintMargin': '0.00000000', 'marginBalance': '0.00000000', 'maxWithdrawAmount': '0.00000000', 'openOrderInitialMargin': '0.00000000', 'positionInitialMargin': '0.00000000', 'unrealizedProfit': '0.00000000', 'updateTime': 0, 'walletBalance': '0.00000000'}, {'asset': 'BTC', 'availableBalance': '0.00000000', 'crossUnPnl': '0.00000000', 'crossWalletBalance': '0.00000000', 'initialMargin': '0.00000000', 'maintMargin': '0.00000000', 'marginBalance': '0.00000000', 'maxWithdrawAmount': '0.00000000', 'openOrderInitialMargin': '0.00000000', 'positionInitialMargin': '0.00000000', 'unrealizedProfit': '0.00000000', 'updateTime': 0, 'walletBalance': '0.00000000'}, {'asset': 'USDT', 'availableBalance': '0.00000000', 'crossUnPnl': '0.00000000', 'crossWalletBalance': '-7675.81507859', 'initialMargin': '0.00000000', 'maintMargin': '0.00000000', 'marginBalance': '-7675.81507859', 'maxWithdrawAmount': '0.00000000', 'openOrderInitialMargin': '0.00000000', 'positionInitialMargin': '0.00000000', 'unrealizedProfit': '0.00000000', 'updateTime': 1768553009156, 'walletBalance': '-7675.81507859'}, {'asset': 'USD1', 'availableBalance': '0.00000000', 'crossUnPnl': '0.00000000', 'crossWalletBalance': '0.00000000', 'initialMargin': '0.00000000', 'maintMargin': '0.00000000', 'marginBalance': '0.00000000', 'maxWithdrawAmount': '0.00000000', 'openOrderInitialMargin': '0.00000000', 'positionInitialMargin': '0.00000000', 'unrealizedProfit': '0.00000000', 'updateTime': 0, 'walletBalance': '0.00000000'}, {'asset': 'USDC', 'availableBalance': '0.00000000', 'crossUnPnl': '0.00000000', 'crossWalletBalance': '0.00000000', 'initialMargin': '0.00000000', 'maintMargin': '0.00000000', 'marginBalance': '0.00000000', 'maxWithdrawAmount': '0.00000000', 'openOrderInitialMargin': '0.00000000', 'positionInitialMargin': '0.00000000', 'unrealizedProfit': '0.00000000', 'updateTime': 1768501108156, 'walletBalance': '0.00000000'}], 'availableBalance': '0.00000000', 'maxWithdrawAmount': '0.00000000', 'positions': [], 'totalCrossUnPnl': '0.00000000', 'totalCrossWalletBalance': '-7675.81507859', 'totalInitialMargin': '0.00000000', 'totalMaintMargin': '0.00000000', 'totalMarginBalance': '-7675.81507859', 'totalOpenOrderInitialMargin': '0.00000000', 'totalPositionInitialMargin': '0.00000000', 'totalUnrealizedProfit': '0.00000000', 'totalWalletBalance': '-7675.81507859'}, 'error': ''}

In [20]:
# usdmPositionsDf['absnotional'] = usdmPositionsDf['notional'].astype(float).abs()
# usdmPositionsDf.sort_values('absnotional', ascending=False)
usdmAssetsDf

,asset,availableBalance,crossUnPnl,crossWalletBalance,initialMargin,maintMargin,marginBalance,maxWithdrawAmount,openOrderInitialMargin,positionInitialMargin,unrealizedProfit,updateTime,walletBalance
0,FDUSD,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0,0.00000000
1,LDUSDT,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0,0.00000000
2,BFUSD,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0,0.00000000
3,BNB,0.29513250,0.00000000,0.29513250,0.00000000,0.00000000,0.29513250,0.29513250,0.00000000,0.00000000,0.00000000,1768553009156,0.29513250
4,ETH,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0,0.00000000
5,RWUSD,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0,0.00000000
6,BTC,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0,0.00000000
7,USDT,0.00000000,0.00000000,-7675.81507859,0.00000000,0.00000000,-7675.81507859,0.00000000,0.00000000,0.00000000,0.00000000,1768553009156,-7675.81507859
8,USD1,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0,0.00000000
9,USDC,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,0.00000000,1768501108156,0.00000000

In [5]:
# import requests
# import json

# headers = {
#     'Content-Type': 'application/json'
# }



# if __name__ == '__main__':
#     env = 'bn_v5_pm_pro15'
#     url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
#     data = {
#         'env':env,
#         'method': 'GET',    # GET/POST
#         'private': True,    # True/False
#         'url': "https://dapi.binance.com/dapi/v1/balance",
#     }

#     print(f'{url}: {data}')
#     response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
# #     response = requests.post(url, headers=headers, data=json.dumps(data))
#     # print(response.text)
#     # print(response.json())
# coinmPositionsDf = pd.DataFrame(response.json()['data'])
# print(coinmPositionsDf)
                              
# # usdmAssetsDf = pd.DataFrame(response.json()['data']['assets'])
# # usdmPositionsDf['maintMargin'] = usdmPositionsDf['maintMargin'].astype(float)
# # usdmPositionsDf['unrealizedProfit'] = usdmPositionsDf['unrealizedProfit'].astype(float)

In [41]:
binanceController = AutoParamController("binance3", proxies)
binanceController.login()
binanceController.initSymbolsList()

chenjunzhe 285533
<Response [200]> <html><head><script>location.reload()</script></head></html>
 {'Server': 'openresty', 'Date': 'Sat, 20 Dec 2025 16:00:27 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Set-Cookie': 'auth=1766268027:chenjunzhe:Pgzuf2W3ueHCrjs4DNwqZ7HzovI=; Expires=Sat, 20-Dec-25 22:00:27 GMT; Max-Age=21600; Path=/; HttpOnly', 'Expires': 'Sat, 20 Dec 2025 16:00:26 GMT', 'Cache-Control': 'no-cache', 'X-Frame-Options': 'sameorigin', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000', 'Content-Encoding': 'gzip'}
chenjunzhe 502869 https://mmadminjp3.digifinex.org/
<Response [200]>
bn_v5_pm_arbSa的symbol_list初始化失败
bn_v5_pm_arbSa2的symbol_list初始化失败

In [50]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
    env = 'bn_v5_pm_pro26'
    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'GET',    # GET/POST
        'private': True,    # True/False
        'url': "https://api.binance.com/api/v3/account",
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    # print(response.text)
    # print(response.json()['assets'])
spotPositionsDf = pd.DataFrame(response.json()['data']['balances'])
# usdmAssetsDf = pd.DataFrame(response.json()['data']['assets'])
# usdmPositionsDf['maintMargin'] = usdmPositionsDf['maintMargin'].astype(float)
# usdmPositionsDf['unrealizedProfit'] = usdmPositionsDf['unrealizedProfit'].astype(float)

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro26', 'method': 'GET', 'private': True, 'url': 'https://api.binance.com/api/v3/account'}

In [51]:
response.json()['data']['balances']

[{'asset': 'BTC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'LTC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ETH', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NEO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BNB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'QTUM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'EOS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SNT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BNT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'GAS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BCC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'USDT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'HSR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'OAX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DNT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MCO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ICN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ZRX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'OMG', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'WTC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'YOYO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'LRC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TRX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SNGLS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'STRAT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BQX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'FUN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'KNC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CDT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XVG', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'IOTA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SNM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'LINK', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CVC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TNT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'REP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MDA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MTL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SALT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NULS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SUB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'STX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MTH', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ADX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ETC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ENG', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ZEC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'AST', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'GNT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DGD', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BAT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DASH', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'POWR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BTG', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'REQ', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XMR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'EVX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'VIB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ENJ', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'VEN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ARK', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XRP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MOD', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'STORJ', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'KMD', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'RCN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'EDO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DATA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DLT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MANA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'PPT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'RDN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'GXS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'AMB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ARN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BCPT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CND', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'GVT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'POE', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BTS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'FUEL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XZC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'QSP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'LSK', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BCD', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TNB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ADA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'LEND', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XLM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CMT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'WAVES', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'WABI', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'GTO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ICX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'OST', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ELF', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'AION', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'WINGS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BRD', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NEBL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NAV', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'VIBE', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'LUN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TRIG', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'APPC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CHAT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'RLC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'INS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'PIVX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'IOST', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'STEEM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NANO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'AE', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'VIA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BLZ', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SYS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'RPX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NCASH', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'POA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ONT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ZIL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'STORM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XEM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'WAN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'WPR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'QLC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'GRS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CLOAK', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'LOOM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BCN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TUSD', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ZEN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SKYCOIN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'THETA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'IOTX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'QKC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'AGI', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NXS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NPXS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'KEY', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NAS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MFT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DENT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'IQ', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ARDR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'HOT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'VET', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DOCK', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'POLY', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'VTHO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ONG', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'PHX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'HC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'GO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'PAX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'RVN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DCR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'USDC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MITH', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BCHABC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BCHSV', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'REN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BTT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'USDS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'FET', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TFUEL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CELR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MATIC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ATOM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'PHB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ONE', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'FTM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BTCB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'USDSB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CHZ', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'COS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ALGO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ERD', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DOGE', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BGBP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DUSK', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ANKR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'WIN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TUSDB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'COCOS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'PERL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TOMO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BUSD', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BAND', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BEAM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'HBAR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XTZ', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NGN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DGB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NKN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'GBP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'EUR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'KAVA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'RUB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'UAH', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ARPA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TRY', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CTXC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'USD', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'AERGO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BCH', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TROY', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'IDR', 'free': '0.00', 'locked': '0.00'},
 {'asset': 'COP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MXN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ARS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BRL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'VITE', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'FTT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'PLN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CZK', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'RON', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'AUD', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'OGN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DREP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BULL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BEAR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ETHBULL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ETHBEAR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XRPBULL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XRPBEAR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'EOSBULL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'EOSBEAR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'JPY', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TCT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'WRX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'LTO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ZAR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MBL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'COTI', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BKRW', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BNBBULL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BNBBEAR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'HIVE', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'STPT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SOL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'IDRT', 'free': '0.00', 'locked': '0.00'},
 {'asset': 'CTSI', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CHR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BTCUP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BTCDOWN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'HNT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'JST', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'FIO', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BIDR', 'free': '0.00', 'locked': '0.00'},
 {'asset': 'STMX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MDT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'PNT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'COMP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'IRIS', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'MKR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SXP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SNX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DAI', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ETHUP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ETHDOWN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ADAUP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ADADOWN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'LINKUP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'LINKDOWN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DOT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'RUNE', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BNBUP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BNBDOWN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XTZUP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XTZDOWN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'AVA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BAL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'YFI', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SRM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'ANT', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'CRV', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SAND', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'OCEAN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'NMR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'LUNA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'IDEX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'RSR', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'PAXG', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'WNXM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TRB', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'EGLD', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BZRX', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'WBTC', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'KSM', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'SUSHI', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'YFII', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DIA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'BEL', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'UMA', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'EOSUP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TRXUP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'EOSDOWN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'TRXDOWN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XRPUP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'XRPDOWN', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DOTUP', 'free': '0.00000000', 'locked': '0.00000000'},
 {'asset': 'DOTDOWN', 'free': '0.00000000', 'locked': '0.00000000'},

In [52]:
spotPositionsDf['free'] = spotPositionsDf['free'].astype(float)
spotPositionsDf['locked'] = spotPositionsDf['locked'].astype(float)

In [53]:
spotPositionsDf[(spotPositionsDf['free']!=0)|(spotPositionsDf['locked']!=0)]

    asset     free  locked
680  DOOD 2000.000   0.000

In [54]:
# spotPositionsDf[spotPositionsDf['']]

In [69]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
    env = 'bn_v5_pm_pro26'
    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'GET',    # GET/POST
        'private': True,    # True/False
        'url': "https://api.binance.com/sapi/v1/margin/account",
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    # print(response.text)
    userAssets = pd.DataFrame(response.json()['data']['userAssets'])

# coinmPositionsDf = pd.DataFrame(response.json()['data']['positions'])
pd.set_option('display.max_rows', 400)
userAssets['netAsset'] = userAssets['netAsset'].astype(float)
userAssets[userAssets['netAsset']!=0]

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro26', 'method': 'GET', 'private': True, 'url': 'https://api.binance.com/sapi/v1/margin/account'}

    asset    borrowed           free    interest locked  netAsset
174   BNB  0.00000768     0.00350714  0.00000012      0     0.003
402  USDT           0  2250.59704804           0      0  2250.597

In [70]:
pd.set_option('display.max_rows', 400)
userAssets['netAsset'] = userAssets['netAsset'].astype(float)
userAssets[userAssets['netAsset']!=0]

    asset    borrowed           free    interest locked  netAsset
174   BNB  0.00000768     0.00350714  0.00000012      0     0.003
402  USDT           0  2250.59704804           0      0  2250.597

In [60]:
# binanceController = AutoParamController("binance3", proxies)
# binanceController.login()
# binanceController.initSymbolsList()

import requests
import json

headers = {
    'Content-Type': 'application/json'
}


if __name__ == '__main__':
    env = 'bn_v5_pm_pro26'
#     env = 'bn_v4_pm_test'
    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'POST',    # GET/POST
        'private': True,    # True/False
        'url': 'https://api.binance.com/sapi/v1/asset/dust-btc',
        'params': {'accountType':'MARGIN'},
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    print(response.text)
    print(response.json())
dust_list = list(pd.DataFrame(response.json()['data']['details'])['asset'])
dust_str = ','.join(list(dust_list))
dust_str

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro26', 'method': 'POST', 'private': True, 'url': 'https://api.binance.com/sapi/v1/asset/dust-btc', 'params': {'accountType': 'MARGIN'}}
{"data":{"details":[{"amountFree":"2.73040827","asset":"USDC","assetFullName":"USDC","exchange":"0.00006276","toBNB":"0.00313776","toBNBOffExchange":"0.003075","toBTC":"0.00003125"}],"dribbletPercentage":"0.02","totalTransferBNB":"0.00313776","totalTransferBtc":"0.00003125"},"error":""}

{'data': {'details': [{'amountFree': '2.73040827', 'asset': 'USDC', 'assetFullName': 'USDC', 'exchange': '0.00006276', 'toBNB': '0.00313776', 'toBNBOffExchange': '0.003075', 'toBTC': '0.00003125'}], 'dribbletPercentage': '0.02', 'totalTransferBNB': '0.00313776', 'totalTransferBtc': '0.00003125'}, 'error': ''}

'USDC'

In [61]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}


if __name__ == '__main__':
    env = 'bn_v5_pm_pro26'
#     env = 'bn_v4_pm_test'
    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'POST',    # GET/POST
        'private': True,    # True/False
        'url': 'https://api.binance.com/sapi/v1/asset/dust',
        'params': {'accountType':'MARGIN', 'asset':dust_str}}

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    print(response.text)
    print(response.json())

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro26', 'method': 'POST', 'private': True, 'url': 'https://api.binance.com/sapi/v1/asset/dust', 'params': {'accountType': 'MARGIN', 'asset': 'USDC'}}
{"data":{"totalServiceCharge":"0.00006277","totalTransfered":"0.00313884","transferResult":[{"amount":"2.73040827","fromAsset":"USDC","operateTime":1769444345836,"serviceChargeAmount":"0.00006277","targetAsset":"BNB","tranId":345284002313,"transferedAmount":"0.00313884"}]},"error":""}

{'data': {'totalServiceCharge': '0.00006277', 'totalTransfered': '0.00313884', 'transferResult': [{'amount': '2.73040827', 'fromAsset': 'USDC', 'operateTime': 1769444345836, 'serviceChargeAmount': '0.00006277', 'targetAsset': 'BNB', 'tranId': 345284002313, 'transferedAmount': '0.00313884'}]}, 'error': ''}

In [12]:
# import requests
# import json

# headers = {
#     'Content-Type': 'application/json'
# }



# if __name__ == '__main__':
#     env = 'bn_v5_pm_pro39'
#     url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
#     data = {
#         'env':env,
#         'method': 'POST',    # GET/POST
#         'private': True,    # True/False
#         'url': "https://api.binance.com/sapi/v1/asset/transfer",
#         'params':{"asset":"BTC", "type":"MAIN_MARGIN", "amount":55}
#     }

#     print(f'{url}: {data}')
#     response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
# #     response = requests.post(url, headers=headers, data=json.dumps(data))
#     print(response.text)

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro39', 'method': 'POST', 'private': True, 'url': 'https://api.binance.com/sapi/v1/asset/transfer', 'params': {'asset': 'BTC', 'type': 'MAIN_MARGIN', 'amount': 55}}
{"data":{"code":-1002,"msg":"You are not authorized to execute this request."},"error":""}

In [74]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
    env = 'bn_v5_pm_pro26'
    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'POST',    # GET/POST
        'private': True,    # True/False
        'url': "https://api.binance.com/sapi/v1/margin/borrow-repay",
        'params':{"asset":"USDT", "isIsolated":False, "amount":82.34, "type":"REPAY"}
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    print(response.text)
    # userAssets = pd.DataFrame(response.json()['data']['userAssets'])

# coinmPositionsDf = pd.DataFrame(response.json()['data']['positions'])
# pd.set_option('display.max_rows', 400)
# userAssets['netAsset'] = userAssets['netAsset'].astype(float)
# userAssets[userAssets['netAsset']!=0]

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro26', 'method': 'POST', 'private': True, 'url': 'https://api.binance.com/sapi/v1/margin/borrow-repay', 'params': {'asset': 'USDT', 'isIsolated': False, 'amount': 82.34, 'type': 'REPAY'}}
{"data":{"clientTag":"","tranId":345379517928},"error":""}

In [64]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
    env = 'bn_v5_pm_pro14'
    # env = 'bn_v5_pm_pro21'
    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'GET',    # GET/POST
        'private': True,    # True/False
        'url': "https://api.binance.com/sapi/v1/margin/account",
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    # print(response.text)
    userAssets = pd.DataFrame(response.json()['data']['userAssets'])

# coinmPositionsDf = pd.DataFrame(response.json()['data']['positions'])
pd.set_option('display.max_rows', 400)
userAssets['netAsset'] = userAssets['netAsset'].astype(float)
userAssets[userAssets['netAsset']!=0]

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro14', 'method': 'GET', 'private': True, 'url': 'https://api.binance.com/sapi/v1/margin/account'}

KeyError: 'userAssets'

In [43]:
binanceController = AutoParamController("binance3", proxies)
binanceController.login()
binanceController.initSymbolsList()

chenjunzhe 835320
<Response [200]> <html><head><script>location.reload()</script></head></html>
 {'Server': 'openresty', 'Date': 'Sat, 20 Dec 2025 16:00:50 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Set-Cookie': 'auth=1766268050:chenjunzhe:NaSpWENIN8qHtM1yZ2IvsDMfudo=; Expires=Sat, 20-Dec-25 22:00:50 GMT; Max-Age=21600; Path=/; HttpOnly', 'Expires': 'Sat, 20 Dec 2025 16:00:49 GMT', 'Cache-Control': 'no-cache', 'X-Frame-Options': 'sameorigin', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Strict-Transport-Security': 'max-age=31536000', 'Content-Encoding': 'gzip'}
chenjunzhe 880708 https://mmadminjp3.digifinex.org/
<Response [200]>
bn_v5_pm_arbSa的symbol_list初始化失败
bn_v5_pm_arbSa2的symbol_list初始化失败

In [44]:
# import requests
# import json

# headers = {
#     'Content-Type': 'application/json'
# }



# if __name__ == '__main__':
#     env = 'bn_v5_pm_arbSa2'
#     env = 'bn_v5_pm_pro23'
#     url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
#     data = {
#         'env':env,
#         'method': 'POST',    # GET/POST
#         'private': True,    # True/False
#         'url': "https://api.binance.com/sapi/v1/convert/getQuote",
#         'params':{"fromAsset":"BNB", "toAsset":"USDT", "fromAmount":0.00049608}
#     }

#     print(f'{url}: {data}')
#     response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     print(response.text)
# #     response = requests.post(url, headers=headers, data=json.dumps(data))
#     # print(response.text)

# spotBalancesDf = pd.DataFrame(response.json()['data']['balances'])
# # pd.set_option('display.max_rows', 400)
# # userAssets['netAsset'] = userAssets['netAsset'].astype(float)
# # userAssets[userAssets['netAsset']!=0]
# spotBalancesDf['free'] = spotBalancesDf['free'].astype(float)
# spotBalancesDf[spotBalancesDf['free']!=0]

In [72]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
    env = 'bn_v5_pm_pro26'
    # env = 'bn_v5_pm_pro23'
    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'POST',    # GET/POST
        'private': True,    # True/False
        'url': "https://api.binance.com/sapi/v1/convert/getQuote",
        'params':{"fromAsset":"BNB", "toAsset":"USDT", "fromAmount":0.00350714}
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
    print(response.text)
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    # print(response.text)

# spotBalancesDf = pd.DataFrame(response.json()['data']['balances'])
# # pd.set_option('display.max_rows', 400)
# # userAssets['netAsset'] = userAssets['netAsset'].astype(float)
# # userAssets[userAssets['netAsset']!=0]
# spotBalancesDf['free'] = spotBalancesDf['free'].astype(float)
# spotBalancesDf[spotBalancesDf['free']!=0]

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro26', 'method': 'POST', 'private': True, 'url': 'https://api.binance.com/sapi/v1/convert/getQuote', 'params': {'fromAsset': 'BNB', 'toAsset': 'USDT', 'fromAmount': 0.00350714}}
{"data":{"fromAmount":"0.00350714","inverseRatio":"0.00113592","ratio":"880.347","toAmount":"3.08750012","validTimestamp":1769483802689},"error":""}

In [66]:
# 闪兑处理最后一点bnb
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
#     env = 'bn_v5_pm_pro23'
#     url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
#     data = {
#         'env':env,
#         'method': 'POST',    # GET/POST
#         'private': True,    # True/False
#         'url': "https://api.binance.com/sapi/v1/convert/getQuote",
#         'params':{"fromAsset":"BNB", "toAsset":"USDT", "fromAmount":0.00049608}
#     }

#     print(f'{url}: {data}')
#     response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
#     print(response.text)
#     quoteId = response.json()['data']['quoteId']
# # usdmPositionsDf['maintMargin'] = usdmPositionsDf['maintMargin'].astype(float)
# # usdmPositionsDf['unrealizedProfit'] = usdmPositionsDf['unrealizedProfit'].astype(float)

    url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'POST',    # GET/POST
        'private': True,    # True/False
        'url': "https://api.binance.com/sapi/v1/convert/acceptQuote",
        'params':{"quoteId":"23dbe4499c164a3d9fa0a9d9d0a35fde"}
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    print(response.text)
    print(response.json())
# usdmPositionsDf['maintMargin'] = usdmPositionsDf['maintMargin'].astype(float)
# usdmPositionsDf['unrealizedProfit'] = usdmPositionsDf['unrealizedProfit'].astype(float)

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro12', 'method': 'POST', 'private': True, 'url': 'https://api.binance.com/sapi/v1/convert/acceptQuote', 'params': {'quoteId': '23dbe4499c164a3d9fa0a9d9d0a35fde'}}
{"data":{"code":345231,"msg":"System failed to execute the quote, which has expired. Please request a quote again."},"error":""}

{'data': {'code': 345231, 'msg': 'System failed to execute the quote, which has expired. Please request a quote again.'}, 'error': ''}

In [155]:
# # 闪兑处理最后一点bnb
# import requests
# import json

# headers = {
#     'Content-Type': 'application/json'
# }



# if __name__ == '__main__':
#     env = 'bn_v5_pm_pro21'
#     url = f'https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request'
#     data = {
#         'env':env,
#         'method': 'POST',    # GET/POST
#         'private': True,    # True/False
#         'url': "https://api.binance.com/sapi/v1/convert/acceptQuote",
#         'params':{"quoteId":"46796337c233458e8ae3c6e3198f713c"}
#     }

#     print(f'{url}: {data}')
#     response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
# #     response = requests.post(url, headers=headers, data=json.dumps(data))
#     print(response.text)
#     print(response.json())
# # usdmPositionsDf['maintMargin'] = usdmPositionsDf['maintMargin'].astype(float)
# # usdmPositionsDf['unrealizedProfit'] = usdmPositionsDf['unrealizedProfit'].astype(float)

https://mmadminjp3.digifinex.org/api/cf_strategy/raw_request: {'env': 'bn_v5_pm_pro21', 'method': 'POST', 'private': True, 'url': 'https://api.binance.com/sapi/v1/convert/acceptQuote', 'params': {'quoteId': '46796337c233458e8ae3c6e3198f713c'}}
{"data":{"code":345231,"msg":"System failed to execute the quote, which has expired. Please request a quote again."},"error":""}

{'data': {'code': 345231, 'msg': 'System failed to execute the quote, which has expired. Please request a quote again.'}, 'error': ''}

In [61]:
json.dumps(data)

'{"env": "bn_v5_pm_pro21", "method": "POST", "private": true, "url": "https://api.binance.com/sapi/v1/convert/getQuote", "params": {"fromAsset": "BNB", "toAsset": "USDT", "fromAmount": 0.00076955}}'

In [19]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
    env = 'bybit5_v5_by3'
    url = f'https://mmadmin.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'POST',    # GET/POST
        'private': True,    # True/False
        'url': "https://api.bybit.com/v5/asset/transfer/inter-transfer",
        'params':{"coin":"BTC", "amount":5, "fromAccountType":"FUND", "toAccountType":"UNIFIED"}
    }

    print(f'{url}: {data}')
    response= binanceController.verified_session.request("POST", url, cookies = binanceController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    # print(response.text)
    print(response.json())
# usdmPositionsDf = pd.DataFrame(response.json()['data']['positions'])
# usdmAssetsDf = pd.DataFrame(response.json()['data']['assets'])
# usdmPositionsDf['maintMargin'] = usdmPositionsDf['maintMargin'].astype(float)
# usdmPositionsDf['unrealizedProfit'] = usdmPositionsDf['unrealizedProfit'].astype(float)

https://mmadmin.digifinex.org/api/cf_strategy/raw_request: {'env': 'bybit5_v5_by3', 'method': 'POST', 'private': True, 'url': 'https://api.bybit.com/v5/asset/transfer/inter-transfer', 'params': {'coin': 'BTC', 'amount': 5, 'fromAccountType': 'FUND', 'toAccountType': 'UNIFIED'}}

JSONDecodeError: Extra data: line 1 column 5 (char 4)

In [27]:
okxController = AutoParamController("okx", proxies)
# verfied_session, verfied_cookies = login(prefix='mmadminjp')
okxController.login()
okxController.initSymbolsList()

chenjunzhe 963644
<Response [200]> <html><head><script>location.reload()</script></head></html>
 {'Date': 'Mon, 05 Jan 2026 12:05:20 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Set-Cookie': 'auth=1767625520:chenjunzhe:sc0mc9QC42mNfmQr7VvHzvcnhGw=; Expires=Mon, 05-Jan-26 15:05:20 GMT; Max-Age=10800; Path=/; HttpOnly', 'Expires': 'Mon, 05 Jan 2026 12:05:19 GMT', 'Cache-Control': 'no-cache', 'Content-Encoding': 'gzip'}
chenjunzhe 577439 https://mmadmin.digifinex.org/
<Response [200]>
okx_v4_u_test的symbol_list初始化失败
okx_v4_u_test2的symbol_list初始化失败
okx_v4_u_test5的symbol_list初始化失败
okx_v4_u_test6的symbol_list初始化失败
okx_v4_u_test7的symbol_list初始化失败
okx_v4_u_test9的symbol_list初始化失败
okx_v4_u_test10的symbol_list初始化失败
okx_v4_u_test11的symbol_list初始化失败
okx_v4_u_test16的symbol_list初始化失败
okx_v4_u_test17的symbol_list初始化失败
okx_v4_u_test18的symbol_list初始化失败
okx_v4_u_test19的symbol_list初始化失败
okx_v4_u_test20的symbol_list初始化失败
okx_v4_u_test21的symbol_list初始化失败
okx_v4_u_test22的symbol_list初始化失败
okx_v4_u_test23的symbol_list初始化失败
okx_v4_u_test25的symbol_list初始化失败
okx_v4_u_test27的symbol_list初始化失败
okx_v4_u_test28的symbol_list初始化失败
okx_v4_u_test29的symbol_list初始化失败
okx_v4_u_test30的symbol_list初始化失败
okx_v4_u_test31的symbol_list初始化失败
okx_v4_u_test32的symbol_list初始化失败
okex5_v4_maker_cross_test的symbol_list初始化失败
okex5_v4_maker_cross_test2的symbol_list初始化失败
okex5_v4_maker_cross_test3的symbol_list初始化失败
okex5_v4_maker_cross_test5的symbol_list初始化失败
okex5_v4_maker_cross_test6的symbol_list初始化失败
okex5_v4_maker_cross_test7的symbol_list初始化失败
okex5_v4_maker_cross_test9的symbol_list初始化失败
okex5_v4_maker_cross_test10的symbol_list初始化失败
okex5_v4_maker_cross_test11的symbol_list初始化失败
okex5_v4_maker_cross_test12的symbol_list初始化失败
okex5_v4_maker_cross_test16的symbol_list初始化失败
okex5_v4_maker_cross_test17的symbol_list初始化失败
okex5_v4_maker_cross_test18的symbol_list初始化失败
okex5_v4_maker_cross_test19的symbol_list初始化失败
okex5_v4_maker_cross_test20的symbol_list初始化失败
okex5_v4_maker_cross_test21的symbol_list初始化失败
okex5_v4_maker_cross_test22的symbol_list初始化失败
okex5_v4_maker_cross_test23的symbol_list初始化失败
okex5_v4_maker_cross_test25的symbol_list初始化失败
okex5_v4_maker_cross_test27的symbol_list初始化失败
okex5_v4_maker_cross_test28的symbol_list初始化失败
okex5_v4_maker_cross_test29的symbol_list初始化失败
okex5_v4_maker_cross_test30的symbol_list初始化失败
okex5_v4_maker_cross_test31的symbol_list初始化失败
okex5_v4_maker_cross_test32的symbol_list初始化失败
okx_v5_test1的symbol_list初始化失败

In [45]:
import requests
import json

headers = {
    'Content-Type': 'application/json'
}



if __name__ == '__main__':
    env = 'okx_v5_test3'
    url = f'https://mmadmin.digifinex.org/api/cf_strategy/raw_request'
    data = {
        'env':env,
        'method': 'GET',    # GET/POST
        'private': True,    # True/False
        'url': "/account/positions",
        # 'params':{}
    }

    print(f'{url}: {data}')
    response= okxController.verified_session.request("POST", url, cookies = okxController.verified_cookies,  headers=headers, data=json.dumps(data))
#     response = requests.post(url, headers=headers, data=json.dumps(data))
    print(response.text)
    print(response.json())

https://mmadmin.digifinex.org/api/cf_strategy/raw_request: {'env': 'okx_v5_test3', 'method': 'GET', 'private': True, 'url': '/account/positions'}
{"data":{"code":"0","data":[],"msg":""},"error":""}

{'data': {'code': '0', 'data': [], 'msg': ''}, 'error': ''}

In [46]:
pd.DataFrame(response.json()['data']['data'])['instId']

KeyError: 'instId'